-- ChatGPT Images 2.5 collection, batch 2 (20 of 21 staged records, approved only)
-- Generated by scripts/export-staged-images-2-5.ts — do not edit by hand.
-- Assumes migration 20260909120000 (provenance columns) is already applied; do not re-run it.
-- Idempotent upsert (ON CONFLICT DO UPDATE). The public library shows only status = 'approved'.
-- Status counts: approved=20.

-- 1. Coloring Book Page from a Photo
INSERT INTO public.curated_prompts (
  id, slug, title, category, user_input, prompt, why_it_works, source, tags, target_model,
  source_type, source_creator, source_url, source_notes, status, generation_ready, gallery_ready,
  needs_reference_images, reference_mode, review_notes, result_count, thumbnail_url, created_at, updated_at
) VALUES (
  'images25-coloring-book-page-from-photo',
  'coloring-book-page-from-photo',
  'Coloring Book Page from a Photo',
  'Image Edits',
  $input$Turn a photo of a person into a clean printable coloring-book page$input$,
  $p$Turn the attached photo into a coloring-book page.

Keep: the person's pose, proportions, hairstyle, facial features and clothing exactly as photographed, so the page is recognisably them.

Change: render everything as clean black line art on pure white. Uniform medium-weight outlines, no shading, no hatching, no grey fills, no gradients. Simplify small details (fabric folds, hair strands) into closed shapes that are easy to colour with a pencil. Add a simple background of a few large closed shapes: a doorway arch behind the figure and two potted plants at the sides, drawn in the same line weight.

Composition: full body centred, generous white margin all round, portrait orientation. No text, no watermark, no signature.$p$,
  $w$The prompt separates what must survive (identity, pose, clothes) from what must change (rendering), which is how Images 2.5 keeps a stylised edit recognisable. "Closed shapes", "uniform line weight" and "no grey fills" are the three constraints that make a page actually printable; without them the model drifts into sketchy shading. Swap the background shapes for any scene.$w$,
  'curated',
  ARRAY['image-edit', 'line-art', 'coloring-book', 'kids', 'print', 'identity-lock']::text[],
  'gpt-image-2.5',
  'depikt_original',
  'Depikt',
  NULL,
  $n$Written for the Images 2.5 identity-preservation improvement. Trend source: the coloring-page requests common in ChatGPT photo-editing threads; no external prompt reused.$n$,
  'approved',
  true,
  false,
  true,
  'edit_source',
  $r$Zoom on the face and hair: closed outlines, no tonal fill. Recognisable likeness; pure black lines on white; no grey; margins clean.
Outcome: Pass on attempt 1 (Sunburst high). Likeness kept (curls, smile, tee, jeans, sneakers); uniform black outlines, no grey fills; arch and two plants as closed shapes; clean margins; no text.
Model used: sunburst; attempts: 1.
Fixtures: portrait-full
Success: Recognisable likeness; pure black lines on white; no grey; margins clean.
Likely failure: Grey shading or hatching creeps in; face simplified past recognition; text or signature added.
Check first: Zoom on the face and hair: closed outlines, no tonal fill.
Attempts: 2. Model: sunburst.
Reference inputs: A clear photo of one person, full body or head-and-shoulders.$r$,
  1,
  '/library/images-2-5/coloring-book-page-from-photo.webp',
  '2026-09-10T03:00:00.000Z',
  '2026-09-10T03:00:00.000Z'
) ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, title = EXCLUDED.title, category = EXCLUDED.category,
  user_input = EXCLUDED.user_input, prompt = EXCLUDED.prompt, why_it_works = EXCLUDED.why_it_works,
  tags = EXCLUDED.tags, target_model = EXCLUDED.target_model, source_type = EXCLUDED.source_type,
  source_creator = EXCLUDED.source_creator, source_url = EXCLUDED.source_url,
  source_notes = EXCLUDED.source_notes, status = EXCLUDED.status,
  generation_ready = EXCLUDED.generation_ready, gallery_ready = EXCLUDED.gallery_ready,
  needs_reference_images = EXCLUDED.needs_reference_images, reference_mode = EXCLUDED.reference_mode,
  review_notes = EXCLUDED.review_notes, result_count = EXCLUDED.result_count,
  thumbnail_url = EXCLUDED.thumbnail_url, updated_at = now();

-- 2. Aged Polaroid with Light Leak
INSERT INTO public.curated_prompts (
  id, slug, title, category, user_input, prompt, why_it_works, source, tags, target_model,
  source_type, source_creator, source_url, source_notes, status, generation_ready, gallery_ready,
  needs_reference_images, reference_mode, review_notes, result_count, thumbnail_url, created_at, updated_at
) VALUES (
  'images25-aged-polaroid-light-leak',
  'aged-polaroid-light-leak',
  'Aged Polaroid with Light Leak',
  'Image Edits',
  $input$Make a crisp photo look like a forgotten 1990s instant print$input$,
  $p$Turn the attached photo into a 1990s instant-film print that has been kept in a drawer for thirty years.

Keep the person, pose, framing and clothing exactly as they are.

Apply, in this order: a slight warm-magenta colour shift with lifted, milky blacks; visible film grain across the whole frame; soft focus that gets softer toward the edges; a faint yellow-orange light leak entering from the bottom-right corner and fading out by the middle of the frame; one small dust speck and one hairline scratch near the top-left. Slightly reduce contrast so highlights bloom.

Present it as the physical print: white instant-film border, wider at the bottom, sitting flat on a plain neutral surface, photographed straight on with soft even light. No handwriting on the border, no text anywhere.$p$,
  $w$Vague "vintage" asks produce a filter. Naming each artefact (colour shift, grain, edge softness, leak position, one scratch) and the order they apply in gives the model a checklist, and pinning the leak to one corner stops it flooding the face. The border-and-surface framing is what sells the physical print. Say "no handwriting" or the model adds a caption.$w$,
  'curated',
  ARRAY['image-edit', 'film', 'polaroid', 'retro', '1990s', 'photo-effect']::text[],
  'gpt-image-2.5',
  'depikt_original',
  'Depikt',
  NULL,
  $n$Adapted from the 'anti-AI aesthetic' trend described by TechRepublic (Sept 2026); prompt text is Depikt's.$n$,
  'approved',
  true,
  false,
  true,
  'edit_source',
  $r$Compare the face and hairline to the source. Same person and pose; leak confined to bottom-right; grain and soft edges visible; clean white border.
Outcome: Pass on attempt 1 (Sunburst high). Same person and pose; warm-magenta shift, grain, soft edges; leak confined to the bottom-right; one scratch top-left; instant-film border on a neutral surface; no caption.
Model used: sunburst; attempts: 1.
Fixtures: portrait-full
Success: Same person and pose; leak confined to bottom-right; grain and soft edges visible; clean white border.
Likely failure: Face changed; leak covering the subject; a fake caption written on the border.
Check first: Compare the face and hairline to the source.
Attempts: 2. Model: sunburst.
Reference inputs: Any sharp photo of a person.$r$,
  1,
  '/library/images-2-5/aged-polaroid-light-leak.webp',
  '2026-09-10T03:00:00.000Z',
  '2026-09-10T03:00:00.000Z'
) ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, title = EXCLUDED.title, category = EXCLUDED.category,
  user_input = EXCLUDED.user_input, prompt = EXCLUDED.prompt, why_it_works = EXCLUDED.why_it_works,
  tags = EXCLUDED.tags, target_model = EXCLUDED.target_model, source_type = EXCLUDED.source_type,
  source_creator = EXCLUDED.source_creator, source_url = EXCLUDED.source_url,
  source_notes = EXCLUDED.source_notes, status = EXCLUDED.status,
  generation_ready = EXCLUDED.generation_ready, gallery_ready = EXCLUDED.gallery_ready,
  needs_reference_images = EXCLUDED.needs_reference_images, reference_mode = EXCLUDED.reference_mode,
  review_notes = EXCLUDED.review_notes, result_count = EXCLUDED.result_count,
  thumbnail_url = EXCLUDED.thumbnail_url, updated_at = now();

-- 3. Roast-Me Caricature from a Photo
INSERT INTO public.curated_prompts (
  id, slug, title, category, user_input, prompt, why_it_works, source, tags, target_model,
  source_type, source_creator, source_url, source_notes, status, generation_ready, gallery_ready,
  needs_reference_images, reference_mode, review_notes, result_count, thumbnail_url, created_at, updated_at
) VALUES (
  'images25-roast-me-caricature',
  'roast-me-caricature',
  'Roast-Me Caricature from a Photo',
  'Image Edits',
  $input$Comic-book caricature of a person built from three of their habits$input$,
  $p$Draw a caricature of the person in the attached photo in a bold comic-book style: thick confident ink outlines, flat cel colours, one hard shadow tone, slightly exaggerated head-to-body ratio.

Likeness first: keep their hair, face shape, skin tone, eyebrows and smile recognisable, only exaggerating the features that are already distinctive.

Three running jokes, shown as props rather than text: (1) an oversized double espresso cup held like a trophy, (2) a phone with an absurdly long unread-messages badge, (3) three sticky notes stuck to the forearm, each with a scribbled to-do, unreadable.

Pose: three-quarter view, mid-gesture as if explaining something at length. Background: a flat warm-ochre colour with a single halftone-dot burst behind the head. No speech bubbles, no words, no logos.$p$,
  $w$Caricature only works when the model knows what to exaggerate and what to keep, so the prompt lists the anchors of likeness and hands the humour to props. Props are safer than text: the model cannot misspell a coffee cup. Replace the three jokes with the person's real habits and keep the rest.$w$,
  'curated',
  ARRAY['image-edit', 'caricature', 'comic', 'humor', 'portrait', 'illustration']::text[],
  'gpt-image-2.5',
  'depikt_original',
  'Depikt',
  NULL,
  $n$Adapted from the 'roast me' caricature trend (TechRepublic, Sept 2026); prompt text is Depikt's.$n$,
  'approved',
  true,
  true,
  true,
  'identity',
  $r$Hair and smile against the source photo. Clearly the same person; comic ink style; all three props present; no text.
Outcome: Pass on attempt 1 (Sunburst high). Clear likeness with hair, brows and smile intact; espresso cup, phone with long red badge, three sticky notes on the forearm; halftone burst on ochre; no speech bubbles or words. Exaggeration is mild; add 'exaggerate more' if you want a harder caricature.
Model used: sunburst; attempts: 1.
Fixtures: portrait-full
Success: Clearly the same person; comic ink style; all three props present; no text.
Likely failure: Generic cartoon face with no likeness; words or speech bubbles added.
Check first: Hair and smile against the source photo.
Attempts: 2. Model: sunburst.
Reference inputs: A clear photo of the person's face.$r$,
  1,
  '/library/images-2-5/roast-me-caricature.webp',
  '2026-09-10T03:00:00.000Z',
  '2026-09-10T03:00:00.000Z'
) ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, title = EXCLUDED.title, category = EXCLUDED.category,
  user_input = EXCLUDED.user_input, prompt = EXCLUDED.prompt, why_it_works = EXCLUDED.why_it_works,
  tags = EXCLUDED.tags, target_model = EXCLUDED.target_model, source_type = EXCLUDED.source_type,
  source_creator = EXCLUDED.source_creator, source_url = EXCLUDED.source_url,
  source_notes = EXCLUDED.source_notes, status = EXCLUDED.status,
  generation_ready = EXCLUDED.generation_ready, gallery_ready = EXCLUDED.gallery_ready,
  needs_reference_images = EXCLUDED.needs_reference_images, reference_mode = EXCLUDED.reference_mode,
  review_notes = EXCLUDED.review_notes, result_count = EXCLUDED.result_count,
  thumbnail_url = EXCLUDED.thumbnail_url, updated_at = now();

-- 4. Pet Reimagined as a Human Athlete
INSERT INTO public.curated_prompts (
  id, slug, title, category, user_input, prompt, why_it_works, source, tags, target_model,
  source_type, source_creator, source_url, source_notes, status, generation_ready, gallery_ready,
  needs_reference_images, reference_mode, review_notes, result_count, thumbnail_url, created_at, updated_at
) VALUES (
  'images25-pet-as-human-marathon-runner',
  'pet-as-human-marathon-runner',
  'Pet Reimagined as a Human Athlete',
  'Image Edits',
  $input$Reimagine a dog as a human marathon runner who still looks like the dog$input$,
  $p$Reimagine the dog in the attached photo as a human marathon runner crossing a finish line.

Carry over the dog's identity into the person: the same golden-blond hair colour as the coat, warm brown eyes, a broad friendly open-mouthed grin, a slightly goofy energetic posture. Someone who knows the dog should recognise the personality.

Scene: mid-stride, arms raised, breaking a finish-line tape; a bright yellow tracksuit; a race bib on the chest with no readable number, just blurred digits; a finisher's medal already around the neck. Background: a city street race with blurred spectators and bunting, late-morning sun.

Photorealistic, 85mm lens look, shallow depth of field. No text anywhere, no logos on the clothing.$p$,
  $w$"Make my pet human" fails when the model just draws a random athlete. Mapping specific traits (coat colour to hair, expression to grin, posture to energy) gives it a bridge from the source to the person. Keeping the bib number blurred sidesteps the one place text would go wrong. Works for any pet: rewrite the four trait lines.$w$,
  'curated',
  ARRAY['image-edit', 'pet', 'transformation', 'humor', 'photorealism', 'portrait']::text[],
  'gpt-image-2.5',
  'depikt_original',
  'Depikt',
  NULL,
  $n$Adapted from the pet-to-human trend (TechRepublic, Sept 2026); prompt text is Depikt's.

SETUP PROMPT: Photorealistic photo of a golden retriever sitting on a lawn in soft morning light, facing the camera with an open-mouthed happy expression, tongue slightly out, ears relaxed, fluffy golden coat. Head-and-chest framing, shallow depth of field, green blurred garden behind. No collar text, no people.$n$,
  'approved',
  true,
  true,
  true,
  'identity',
  $r$Is it a person (not a dog in clothes) and does the hair colour match the coat? A human whose colouring and expression clearly echo the dog; finish-line scene; no readable text.
Outcome: Pass on attempt 1 (Sunburst high). A human runner whose golden hair and open grin echo the dog; yellow kit, blurred bib digits, medal, finish tape, blurred crowd; no readable text or logos.
Model used: sunburst; attempts: 1.
Success: A human whose colouring and expression clearly echo the dog; finish-line scene; no readable text.
Likely failure: Anthropomorphic dog-headed figure instead of a person; readable bib numbers or brand logos.
Check first: Is it a person (not a dog in clothes) and does the hair colour match the coat?
Attempts: 2. Model: sunburst.
Reference inputs: A clear photo of the pet, ideally facing the camera.$r$,
  1,
  '/library/images-2-5/pet-as-human-marathon-runner.webp',
  '2026-09-10T03:00:00.000Z',
  '2026-09-10T03:00:00.000Z'
) ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, title = EXCLUDED.title, category = EXCLUDED.category,
  user_input = EXCLUDED.user_input, prompt = EXCLUDED.prompt, why_it_works = EXCLUDED.why_it_works,
  tags = EXCLUDED.tags, target_model = EXCLUDED.target_model, source_type = EXCLUDED.source_type,
  source_creator = EXCLUDED.source_creator, source_url = EXCLUDED.source_url,
  source_notes = EXCLUDED.source_notes, status = EXCLUDED.status,
  generation_ready = EXCLUDED.generation_ready, gallery_ready = EXCLUDED.gallery_ready,
  needs_reference_images = EXCLUDED.needs_reference_images, reference_mode = EXCLUDED.reference_mode,
  review_notes = EXCLUDED.review_notes, result_count = EXCLUDED.result_count,
  thumbnail_url = EXCLUDED.thumbnail_url, updated_at = now();

-- 5. Transparent Product Cutout
INSERT INTO public.curated_prompts (
  id, slug, title, category, user_input, prompt, why_it_works, source, tags, target_model,
  source_type, source_creator, source_url, source_notes, status, generation_ready, gallery_ready,
  needs_reference_images, reference_mode, review_notes, result_count, thumbnail_url, created_at, updated_at
) VALUES (
  'images25-transparent-product-cutout',
  'transparent-product-cutout',
  'Transparent Product Cutout',
  'Image Edits',
  $input$Isolate a product on a transparent background with clean alpha edges$input$,
  $p$Isolate the product in the attached photo on a fully transparent background.

Keep the product itself pixel-faithful: shape, label text, colours, highlights and the subtle reflections on the metal rim. Do not redraw, restyle, straighten or recolour it.

Remove everything else: the backdrop, the surface it stands on and the contact shadow. Nothing may surround the product: no glow, no outer shadow, no soft halo, no coloured haze outside the silhouette. The product must be 100% opaque everywhere inside its outline; only the outermost one-pixel edge may be anti-aliased. Leave no white halo, no dark fringe and no leftover background pixels in the gap under the rim.

Output a PNG with real transparency, product centred, small even margin on all sides.$p$,
  $w$This is the e-commerce cutout that used to need a masking pass. Naming the artefacts to avoid (halo, fringe, leftovers in cavities) is more useful than "clean edges", because those are the three ways the model fails. Ask for real transparency, not a checkerboard: a rendered checkerboard is the classic false positive. In the API, set background to transparent as well as saying it in the prompt.$w$,
  'curated',
  ARRAY['image-edit', 'product', 'transparent', 'cutout', 'ecommerce', 'packshot']::text[],
  'gpt-image-2.5',
  'depikt_original',
  'Depikt',
  NULL,
  $n$Uses the transparent-background output added to the Images 2.5 API (OpenAI cookbook); prompt text is Depikt's.$n$,
  'approved',
  true,
  false,
  true,
  'edit_source',
  $r$Open on a dark background and inspect the silhouette edge. PNG with real alpha; label text unchanged; no halo; shadow removed.
Outcome: Pass on attempt 2 (Sunburst high) with the revised prompt (now the record prompt). Real alpha: 69% fully transparent, corners at 0, about 1% partial pixels at the silhouette; label unchanged; no shadow. Composited on white and dark grey with no halo. Attempt 1 with the original wording was similar but the extra 'no glow, 100% opaque' lines are kept because they cost nothing. Note: the API returns opaque pixels at alpha 253–254, not 255; harmless in use.
Model used: sunburst; attempts: 2.
Fixtures: product-packshot
Success: PNG with real alpha; label text unchanged; no halo; shadow removed.
Likely failure: Painted checkerboard instead of transparency; label re-typeset; white fringe.
Check first: Open on a dark background and inspect the silhouette edge.
Attempts: 2. Model: sunburst.
Reference inputs: A product photo on a plain background.$r$,
  1,
  '/library/images-2-5/transparent-product-cutout.webp',
  '2026-09-10T03:00:00.000Z',
  '2026-09-10T03:00:00.000Z'
) ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, title = EXCLUDED.title, category = EXCLUDED.category,
  user_input = EXCLUDED.user_input, prompt = EXCLUDED.prompt, why_it_works = EXCLUDED.why_it_works,
  tags = EXCLUDED.tags, target_model = EXCLUDED.target_model, source_type = EXCLUDED.source_type,
  source_creator = EXCLUDED.source_creator, source_url = EXCLUDED.source_url,
  source_notes = EXCLUDED.source_notes, status = EXCLUDED.status,
  generation_ready = EXCLUDED.generation_ready, gallery_ready = EXCLUDED.gallery_ready,
  needs_reference_images = EXCLUDED.needs_reference_images, reference_mode = EXCLUDED.reference_mode,
  review_notes = EXCLUDED.review_notes, result_count = EXCLUDED.result_count,
  thumbnail_url = EXCLUDED.thumbnail_url, updated_at = now();

-- 6. Six-Expression Sticker Sheet
INSERT INTO public.curated_prompts (
  id, slug, title, category, user_input, prompt, why_it_works, source, tags, target_model,
  source_type, source_creator, source_url, source_notes, status, generation_ready, gallery_ready,
  needs_reference_images, reference_mode, review_notes, result_count, thumbnail_url, created_at, updated_at
) VALUES (
  'images25-six-expression-sticker-sheet',
  'six-expression-sticker-sheet',
  'Six-Expression Sticker Sheet',
  'Open-Ended Creative',
  $input$One character, six expressions, as a transparent sticker sheet$input$,
  $p$Create a sticker sheet of one original character: a round-faced orange cat in a tiny green knitted beanie, drawn in a clean kawaii style with thick dark-brown outlines and flat colours.

Six stickers in a 3 x 2 grid, each showing the same character with a different expression, in this order: 1 delighted, 2 sleepy, 3 shocked, 4 smug, 5 crying-laughing, 6 confused. The character must be identical across all six: same beanie, same proportions, same outline weight, same palette. Only the face and small hand gestures change.

Each sticker has a thick white die-cut border with a rounded outline. Even spacing, no overlap, no text, no numbers, no background: fully transparent PNG.$p$,
  $w$Sticker packs are a consistency test disguised as a fun ask. Locking the character with a short spec (species, one accessory, outline, palette) and listing the six expressions by number is what keeps all six the same character. The white die-cut border plus transparent output is what makes them usable straight away in a chat app.$w$,
  'curated',
  ARRAY['sticker', 'character', 'transparent', 'expressions', 'kawaii', 'illustration']::text[],
  'gpt-image-2.5',
  'depikt_original',
  'Depikt',
  NULL,
  $n$Depikt original; the transparent-PNG output is an Images 2.5 API feature.$n$,
  'approved',
  true,
  true,
  false,
  'none',
  $r$Compare sticker 1 and sticker 6 side by side. Six clearly identical characters, six distinct expressions, white die-cut borders, transparent background.
Outcome: Pass on attempt 1 (Sunburst high). Six identical cats (same beanie, outline, palette) with six distinct expressions in the stated order; thick white die-cut borders; transparent PNG (corners alpha 0). A small '?' glyph on sticker 6 is a symbol, not text.
Model used: sunburst; attempts: 1.
Success: Six clearly identical characters, six distinct expressions, white die-cut borders, transparent background.
Likely failure: Beanie or proportions change between stickers; a coloured background; text or numbers.
Check first: Compare sticker 1 and sticker 6 side by side.
Attempts: 2. Model: sunburst.$r$,
  1,
  '/library/images-2-5/six-expression-sticker-sheet.webp',
  '2026-09-10T03:00:00.000Z',
  '2026-09-10T03:00:00.000Z'
) ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, title = EXCLUDED.title, category = EXCLUDED.category,
  user_input = EXCLUDED.user_input, prompt = EXCLUDED.prompt, why_it_works = EXCLUDED.why_it_works,
  tags = EXCLUDED.tags, target_model = EXCLUDED.target_model, source_type = EXCLUDED.source_type,
  source_creator = EXCLUDED.source_creator, source_url = EXCLUDED.source_url,
  source_notes = EXCLUDED.source_notes, status = EXCLUDED.status,
  generation_ready = EXCLUDED.generation_ready, gallery_ready = EXCLUDED.gallery_ready,
  needs_reference_images = EXCLUDED.needs_reference_images, reference_mode = EXCLUDED.reference_mode,
  review_notes = EXCLUDED.review_notes, result_count = EXCLUDED.result_count,
  thumbnail_url = EXCLUDED.thumbnail_url, updated_at = now();

-- 7. Traditional Tattoo Flash Sheet
INSERT INTO public.curated_prompts (
  id, slug, title, category, user_input, prompt, why_it_works, source, tags, target_model,
  source_type, source_creator, source_url, source_notes, status, generation_ready, gallery_ready,
  needs_reference_images, reference_mode, review_notes, result_count, thumbnail_url, created_at, updated_at
) VALUES (
  'images25-tattoo-flash-sheet',
  'tattoo-flash-sheet',
  'Traditional Tattoo Flash Sheet',
  'Open-Ended Creative',
  $input$American-traditional flash sheet with nine designs and no lettering$input$,
  $p$Design an American-traditional tattoo flash sheet on aged cream paper.

Nine designs arranged in a loose 3 x 3 layout with hand-placed spacing, each a self-contained tattoo: a swallow in flight, a dagger through a rose, a lighthouse with waves, a panther head, a ship's anchor with rope, a lit candle, a snake coiled around a heart, a compass rose, a single peony.

Style rules: bold black outlines of even weight, limited palette of red, golden yellow, forest green and black, solid fills with minimal shading, whip-shading only inside the black. Slight ink bleed and paper texture so it reads as a hand-painted sheet, not a vector file.

No banners with words, no lettering, no signature. Portrait orientation.$p$,
  $w$Flash is a well-defined visual language, so the prompt states its rules (line weight, four colours, whip shading) rather than adjectives like "old school". Listing nine subjects avoids the model repeating motifs, and "no banners with words" matters because traditional flash normally carries text the model would garble.$w$,
  'curated',
  ARRAY['tattoo', 'flash-sheet', 'illustration', 'traditional', 'print', 'poster']::text[],
  'gpt-image-2.5',
  'depikt_original',
  'Depikt',
  NULL,
  $n$Depikt original.$n$,
  'approved',
  true,
  true,
  false,
  'none',
  $r$Count the designs and scan for any letters. Nine distinct designs in a consistent flash style; four-colour palette; no lettering.
Outcome: Pass on attempt 1 (Sunburst high). Nine distinct designs in a consistent traditional style, red/yellow/green/black palette, aged paper, no banners or lettering.
Model used: sunburst; attempts: 1.
Success: Nine distinct designs in a consistent flash style; four-colour palette; no lettering.
Likely failure: Banners with misspelled words; photographic shading; duplicated motifs.
Check first: Count the designs and scan for any letters.
Attempts: 1. Model: sunburst.$r$,
  1,
  '/library/images-2-5/tattoo-flash-sheet.webp',
  '2026-09-10T03:00:00.000Z',
  '2026-09-10T03:00:00.000Z'
) ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, title = EXCLUDED.title, category = EXCLUDED.category,
  user_input = EXCLUDED.user_input, prompt = EXCLUDED.prompt, why_it_works = EXCLUDED.why_it_works,
  tags = EXCLUDED.tags, target_model = EXCLUDED.target_model, source_type = EXCLUDED.source_type,
  source_creator = EXCLUDED.source_creator, source_url = EXCLUDED.source_url,
  source_notes = EXCLUDED.source_notes, status = EXCLUDED.status,
  generation_ready = EXCLUDED.generation_ready, gallery_ready = EXCLUDED.gallery_ready,
  needs_reference_images = EXCLUDED.needs_reference_images, reference_mode = EXCLUDED.reference_mode,
  review_notes = EXCLUDED.review_notes, result_count = EXCLUDED.result_count,
  thumbnail_url = EXCLUDED.thumbnail_url, updated_at = now();

-- 8. Packaging Label Text Swap
INSERT INTO public.curated_prompts (
  id, slug, title, category, user_input, prompt, why_it_works, source, tags, target_model,
  source_type, source_creator, source_url, source_notes, status, generation_ready, gallery_ready,
  needs_reference_images, reference_mode, review_notes, result_count, thumbnail_url, created_at, updated_at
) VALUES (
  'images25-packaging-label-text-swap',
  'packaging-label-text-swap',
  'Packaging Label Text Swap',
  'Image Edits',
  $input$Change one line of label text on a product photo and nothing else$input$,
  $p$On the attached can, change only the small line of text under the brand name from "sparkling yuzu" to "sparkling grapefruit".

Match the original typeface, weight, letter-spacing, size, colour and baseline position exactly; centre the new, longer line the same way the old one was centred.

Everything else stays identical: the brand wordmark, the cloud icon, the can's colour, the metal rim, the highlights and reflections, the shadow, the background and the framing. Do not re-render the can; treat this as a label correction.$p$,
  $w$The edit is scoped to one string and describes the typographic properties that must carry over, which is how you get a correction instead of a redesign. Quoting both the old and the new text tells the model exactly what to find and what to replace. "Do not re-render the can" is the sentence that stops it regenerating the whole object.$w$,
  'curated',
  ARRAY['image-edit', 'packaging', 'text-swap', 'exact-text', 'product', 'preserve']::text[],
  'gpt-image-2.5',
  'depikt_original',
  'Depikt',
  NULL,
  $n$Pattern drawn from the Images 2.5 'surgical packaging edit' behaviour documented in the launch post; prompt text is Depikt's.$n$,
  'approved',
  true,
  false,
  true,
  'edit_source',
  $r$Overlay against the source: only the sub-line should differ. Only the sub-line changed; type matches; wordmark, icon, can and lighting untouched.
Outcome: Pass on attempt 1 (Sunburst high). Only the sub-line changed to 'sparkling grapefruit' in the matching typeface, centred; wordmark, cloud icon, can, rim, shadow and background unchanged.
Model used: sunburst; attempts: 1.
Fixtures: product-packshot
Success: Only the sub-line changed; type matches; wordmark, icon, can and lighting untouched.
Likely failure: Whole label re-typeset; can colour shifts; brand name altered.
Check first: Overlay against the source: only the sub-line should differ.
Attempts: 2. Model: sunburst.
Reference inputs: A product photo with legible label text.$r$,
  1,
  '/library/images-2-5/packaging-label-text-swap.webp',
  '2026-09-10T03:00:00.000Z',
  '2026-09-10T03:00:00.000Z'
) ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, title = EXCLUDED.title, category = EXCLUDED.category,
  user_input = EXCLUDED.user_input, prompt = EXCLUDED.prompt, why_it_works = EXCLUDED.why_it_works,
  tags = EXCLUDED.tags, target_model = EXCLUDED.target_model, source_type = EXCLUDED.source_type,
  source_creator = EXCLUDED.source_creator, source_url = EXCLUDED.source_url,
  source_notes = EXCLUDED.source_notes, status = EXCLUDED.status,
  generation_ready = EXCLUDED.generation_ready, gallery_ready = EXCLUDED.gallery_ready,
  needs_reference_images = EXCLUDED.needs_reference_images, reference_mode = EXCLUDED.reference_mode,
  review_notes = EXCLUDED.review_notes, result_count = EXCLUDED.result_count,
  thumbnail_url = EXCLUDED.thumbnail_url, updated_at = now();

-- 9. Multi-Turn Campaign Localization
INSERT INTO public.curated_prompts (
  id, slug, title, category, user_input, prompt, why_it_works, source, tags, target_model,
  source_type, source_creator, source_url, source_notes, status, generation_ready, gallery_ready,
  needs_reference_images, reference_mode, review_notes, result_count, thumbnail_url, created_at, updated_at
) VALUES (
  'images25-multi-turn-campaign-localization',
  'multi-turn-campaign-localization',
  'Multi-Turn Campaign Localization',
  'Image Edits',
  $input$Translate a campaign image's copy across two turns without moving anything$input$,
  $p$Run these as separate turns on the attached campaign image, feeding each result into the next. Each turn changes only the quoted text; layout, product, photo, colours and type styling stay exactly as they are.

Turn 1: Change the headline "Bright as noon." to the French "Lumineux comme midi." and the button text "Now in stores" to "En magasin". Keep the same typeface, size, weight and positions; do not move the can or any other element.
Turn 2: Change the headline "Lumineux comme midi." to the German "Hell wie der Mittag." and the button text "En magasin" to "Jetzt im Handel". Keep the same typeface, size, weight and positions; do not move the can or any other element.$p$,
  $w$Localization is the multi-turn case that pays off most: one master image, many markets. Each turn quotes the current and the new strings and restates the preservation rule, so drift has nowhere to start. Two turns is the sweet spot; the model softens after long chains, so run one language per turn and branch from the master rather than chaining five.$w$,
  'curated',
  ARRAY['image-edit', 'multi-turn', 'localization', 'exact-text', 'campaign', 'preserve']::text[],
  'gpt-image-2.5',
  'depikt_original',
  'Depikt',
  NULL,
  $n$Structure adapted from OpenAI's multi-turn localization examples; strings and scene are Depikt's.

SETUP PROMPT: Vertical 4:5 paid-social campaign image for a sparkling yuzu drink called KUMO. A pale-yellow can with the wordmark "KUMO" stands on a sunlit concrete ledge, hard noon shadow, a slice of yuzu beside it, clear blue sky behind. Top-left, a bold navy sans-serif headline in two lines: "Bright as noon." Bottom-left, a small navy rounded button with white text "Now in stores". No other text. Clean, minimal, lots of sky.$n$,
  'approved',
  true,
  false,
  true,
  'edit_source',
  $r$Diff turn 2 against the master outside the two text regions. After turn 2: German headline and button, everything else pixel-close to the master; turn 1 result correct in French.
Outcome: Pass on attempt 1 (Sunburst high), two-turn chain. Turn 1: French headline and button exact, nothing moved. Turn 2: German headline and button exact, can, lemon, ledge and type styling identical to the master. No drift across the chain.
Model used: sunburst; attempts: 1.
Success: After turn 2: German headline and button, everything else pixel-close to the master; turn 1 result correct in French.
Likely failure: Can or button moves; typeface changes; a turn reverts the other string.
Check first: Diff turn 2 against the master outside the two text regions.
Attempts: 1. Model: sunburst.
Reference inputs: The master campaign image, generated with the setup prompt.$r$,
  1,
  '/library/images-2-5/multi-turn-campaign-localization.webp',
  '2026-09-10T03:00:00.000Z',
  '2026-09-10T03:00:00.000Z'
) ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, title = EXCLUDED.title, category = EXCLUDED.category,
  user_input = EXCLUDED.user_input, prompt = EXCLUDED.prompt, why_it_works = EXCLUDED.why_it_works,
  tags = EXCLUDED.tags, target_model = EXCLUDED.target_model, source_type = EXCLUDED.source_type,
  source_creator = EXCLUDED.source_creator, source_url = EXCLUDED.source_url,
  source_notes = EXCLUDED.source_notes, status = EXCLUDED.status,
  generation_ready = EXCLUDED.generation_ready, gallery_ready = EXCLUDED.gallery_ready,
  needs_reference_images = EXCLUDED.needs_reference_images, reference_mode = EXCLUDED.reference_mode,
  review_notes = EXCLUDED.review_notes, result_count = EXCLUDED.result_count,
  thumbnail_url = EXCLUDED.thumbnail_url, updated_at = now();

-- 10. Board Game Box Cover with Exact Title
INSERT INTO public.curated_prompts (
  id, slug, title, category, user_input, prompt, why_it_works, source, tags, target_model,
  source_type, source_creator, source_url, source_notes, status, generation_ready, gallery_ready,
  needs_reference_images, reference_mode, review_notes, result_count, thumbnail_url, created_at, updated_at
) VALUES (
  'images25-board-game-box-cover',
  'board-game-box-cover',
  'Board Game Box Cover with Exact Title',
  'Posters',
  $input$Square board-game box art with an exact title and player count badge$input$,
  $p$Design the top of a square board-game box.

Title, exactly: "TIDEWATER" in a tall serif with a slight sea-worn texture, set in cream across the upper third. Beneath it, smaller, in the same cream: "A game of lighthouses and lost cargo".

Illustration: a night harbour seen from above at an angle, three lighthouses sweeping beams across dark water, small cargo ships leaving glowing wakes, a coastline of stone cottages. Painterly, rich navy and teal with warm amber light, fine detail in the ships.

Bottom-right corner, a small round cream badge with three lines: "2–4", "45 MIN", "AGE 10+". Bottom-left, a thin cream frame line with no other text. Square 1:1, print-ready feel, no publisher logo.$p$,
  $w$Box art has a fixed anatomy (title zone, hero illustration, spec badge), so the prompt assigns each its region and quotes every string. Putting the numbers in a badge with three short lines keeps them legible; a sentence of numbers is where text usually breaks. Swap title, tagline and illustration for any game.$w$,
  'curated',
  ARRAY['poster', 'board-game', 'packaging', 'exact-text', 'illustration', 'typography']::text[],
  'gpt-image-2.5',
  'depikt_original',
  'Depikt',
  NULL,
  $n$Depikt original.$n$,
  'approved',
  true,
  true,
  false,
  'none',
  $r$Read every string aloud. Title and tagline letter-perfect; badge shows 2–4 / 45 MIN / AGE 10+; painterly harbour.
Outcome: Pass on attempt 1 (Sunburst high). 'TIDEWATER' and the tagline letter-perfect in textured cream serif; painterly night harbour with three sweeping lighthouses and cargo ships; badge reads 2–4 / 45 MIN / AGE 10+; thin frame line; no publisher logo or extra text.
Model used: sunburst; attempts: 1.
Success: Title and tagline letter-perfect; badge shows 2–4 / 45 MIN / AGE 10+; painterly harbour.
Likely failure: Extra invented text; badge numbers wrong; title texture eats letterforms.
Check first: Read every string aloud.
Attempts: 2. Model: sunburst.$r$,
  1,
  '/library/images-2-5/board-game-box-cover.webp',
  '2026-09-10T03:00:00.000Z',
  '2026-09-10T03:00:00.000Z'
) ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, title = EXCLUDED.title, category = EXCLUDED.category,
  user_input = EXCLUDED.user_input, prompt = EXCLUDED.prompt, why_it_works = EXCLUDED.why_it_works,
  tags = EXCLUDED.tags, target_model = EXCLUDED.target_model, source_type = EXCLUDED.source_type,
  source_creator = EXCLUDED.source_creator, source_url = EXCLUDED.source_url,
  source_notes = EXCLUDED.source_notes, status = EXCLUDED.status,
  generation_ready = EXCLUDED.generation_ready, gallery_ready = EXCLUDED.gallery_ready,
  needs_reference_images = EXCLUDED.needs_reference_images, reference_mode = EXCLUDED.reference_mode,
  review_notes = EXCLUDED.review_notes, result_count = EXCLUDED.result_count,
  thumbnail_url = EXCLUDED.thumbnail_url, updated_at = now();

-- 11. Four-Season Variant Strip from One Photo
INSERT INTO public.curated_prompts (
  id, slug, title, category, user_input, prompt, why_it_works, source, tags, target_model,
  source_type, source_creator, source_url, source_notes, status, generation_ready, gallery_ready,
  needs_reference_images, reference_mode, review_notes, result_count, thumbnail_url, created_at, updated_at
) VALUES (
  'images25-four-season-cabin-strip',
  'four-season-cabin-strip',
  'Four-Season Variant Strip from One Photo',
  'Image Edits',
  $input$One cabin photo rendered as four seasons side by side, nothing else changed$input$,
  $p$Using the attached photo as the master, produce one wide image containing four equal square panels side by side, left to right: summer, autumn, winter, spring.

Every panel keeps the exact same cabin, camera position, lens, framing, porch, windows, path and tree positions as the master. Only these change per panel: foliage colour and density, ground cover (grass, fallen leaves, snow, wildflowers), sky and light (summer noon, autumn golden hour, winter overcast with snowfall, spring soft morning), and small seasonal props (a garden chair in summer, a pumpkin by the door in autumn, smoke from the chimney in winter, a bicycle in spring).

Thin white gutters between panels, no borders otherwise, no labels, no text.$p$,
  $w$One source, four outputs, one image: this shows the preservation behaviour that makes Images 2.5 useful for campaigns. Listing what may change per panel (foliage, ground, sky, one prop) and stating that everything else is locked is the whole trick. The strip format lets you check consistency by eye in a single glance.$w$,
  'curated',
  ARRAY['image-edit', 'seasons', 'variants', 'preserve', 'multi-panel', 'architecture']::text[],
  'gpt-image-2.5',
  'depikt_original',
  'Depikt',
  NULL,
  $n$Depikt original; extends the launch post's seasonal-edit example into a single comparison strip.

SETUP PROMPT: Photorealistic photo of a small timber cabin with a covered porch, two front windows and a stone chimney, seen straight on from a gravel path, a large maple tree to the left and a low wooden fence, clear summer noon light, square 1:1 framing. No people, no text.$n$,
  'approved',
  true,
  true,
  true,
  'edit_source',
  $r$Line up the porch roof edge across all four panels. Four panels, identical geometry, clearly distinct seasons, one prop each, no text.
Outcome: Pass on attempt 1 (Sunburst high). Four square panels, summer to spring, with pumpkin, chimney smoke and bicycle as props and season-correct sky and ground. Cabin, porch and path line up across panels; the winter panel sits very slightly closer than the others.
Model used: sunburst; attempts: 1.
Success: Four panels, identical geometry, clearly distinct seasons, one prop each, no text.
Likely failure: Cabin shape or camera drifts between panels; seasons blend; labels appear.
Check first: Line up the porch roof edge across all four panels.
Attempts: 2. Model: sunburst.
Reference inputs: A photo of a building or scene, generated with the setup prompt.$r$,
  1,
  '/library/images-2-5/four-season-cabin-strip.webp',
  '2026-09-10T03:00:00.000Z',
  '2026-09-10T03:00:00.000Z'
) ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, title = EXCLUDED.title, category = EXCLUDED.category,
  user_input = EXCLUDED.user_input, prompt = EXCLUDED.prompt, why_it_works = EXCLUDED.why_it_works,
  tags = EXCLUDED.tags, target_model = EXCLUDED.target_model, source_type = EXCLUDED.source_type,
  source_creator = EXCLUDED.source_creator, source_url = EXCLUDED.source_url,
  source_notes = EXCLUDED.source_notes, status = EXCLUDED.status,
  generation_ready = EXCLUDED.generation_ready, gallery_ready = EXCLUDED.gallery_ready,
  needs_reference_images = EXCLUDED.needs_reference_images, reference_mode = EXCLUDED.reference_mode,
  review_notes = EXCLUDED.review_notes, result_count = EXCLUDED.result_count,
  thumbnail_url = EXCLUDED.thumbnail_url, updated_at = now();

-- 12. Podcast Cover Art with Exact Title
INSERT INTO public.curated_prompts (
  id, slug, title, category, user_input, prompt, why_it_works, source, tags, target_model,
  source_type, source_creator, source_url, source_notes, status, generation_ready, gallery_ready,
  needs_reference_images, reference_mode, review_notes, result_count, thumbnail_url, created_at, updated_at
) VALUES (
  'images25-podcast-cover-art-exact-title',
  'podcast-cover-art-exact-title',
  'Podcast Cover Art with Exact Title',
  'Posters',
  $input$Square podcast cover that stays legible at thumbnail size$input$,
  $p$Design a square podcast cover, 1:1, that must read at 64 pixels wide.

Title, exactly: "SLOW FIELDS" in a heavy geometric sans, two stacked lines, filling the top half, in off-white. Below it, small: "a walking podcast". No other text.

Artwork: a bold flat-colour illustration of a single figure with a backpack walking along a ridge, seen from behind, against a huge low sun. Three colours only: deep forest green, burnt orange, off-white. No gradients, no photographic texture, no fine detail: every shape must survive being shrunk to an app icon.

Leave a clear margin around the title; nothing overlaps the letters.$p$,
  $w$Cover art fails at thumbnail size, so the prompt designs for the smallest case: three flat colours, one big shape, a heavy typeface, a stated pixel target. Quoting the title and forbidding other text keeps the model from adding an episode number or host name. Rewrite the title and the single figure for any show.$w$,
  'curated',
  ARRAY['poster', 'podcast', 'cover', 'exact-text', 'flat-illustration', 'branding']::text[],
  'gpt-image-2.5',
  'depikt_original',
  'Depikt',
  NULL,
  $n$Depikt original.$n$,
  'approved',
  true,
  true,
  false,
  'none',
  $r$Shrink the result to 64px and read the title. Title exact and dominant; three colours; still legible when viewed small.
Outcome: Pass on attempt 1 (Sunburst high). 'SLOW FIELDS' stacked in a heavy sans filling the top half, 'a walking podcast' beneath; single walking figure against a low sun; forest green, burnt orange, off-white only; reads clearly when shrunk.
Model used: sunburst; attempts: 1.
Success: Title exact and dominant; three colours; still legible when viewed small.
Likely failure: Extra text; gradients; thin type.
Check first: Shrink the result to 64px and read the title.
Attempts: 1. Model: sunburst.$r$,
  1,
  '/library/images-2-5/podcast-cover-art-exact-title.webp',
  '2026-09-10T03:00:00.000Z',
  '2026-09-10T03:00:00.000Z'
) ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, title = EXCLUDED.title, category = EXCLUDED.category,
  user_input = EXCLUDED.user_input, prompt = EXCLUDED.prompt, why_it_works = EXCLUDED.why_it_works,
  tags = EXCLUDED.tags, target_model = EXCLUDED.target_model, source_type = EXCLUDED.source_type,
  source_creator = EXCLUDED.source_creator, source_url = EXCLUDED.source_url,
  source_notes = EXCLUDED.source_notes, status = EXCLUDED.status,
  generation_ready = EXCLUDED.generation_ready, gallery_ready = EXCLUDED.gallery_ready,
  needs_reference_images = EXCLUDED.needs_reference_images, reference_mode = EXCLUDED.reference_mode,
  review_notes = EXCLUDED.review_notes, result_count = EXCLUDED.result_count,
  thumbnail_url = EXCLUDED.thumbnail_url, updated_at = now();

-- 13. Living Room Furniture Swap
INSERT INTO public.curated_prompts (
  id, slug, title, category, user_input, prompt, why_it_works, source, tags, target_model,
  source_type, source_creator, source_url, source_notes, status, generation_ready, gallery_ready,
  needs_reference_images, reference_mode, review_notes, result_count, thumbnail_url, created_at, updated_at
) VALUES (
  'images25-living-room-furniture-swap',
  'living-room-furniture-swap',
  'Living Room Furniture Swap',
  'Image Edits',
  $input$Replace the sofa and rug in a room photo while keeping the room$input$,
  $p$In the attached living-room photo, replace two things and nothing else.

Replace the sofa with a low three-seat sofa in oatmeal bouclé with slim oak legs, same footprint and position as the original. Replace the rug with a flat-weave wool rug in a wide navy-and-cream stripe, same size and placement.

Keep everything else exactly as photographed: walls, windows, daylight direction, floor, plants, side table, lamp, artwork, ceiling and camera position. The new pieces must sit in the room with correct perspective, contact shadows and the same light falling on them as on the rest of the scene.$p$,
  $w$Interior swaps go wrong when the model redecorates the whole room. Naming the two objects, their replacements with materials, and "same footprint and position" keeps the edit surgical; the preservation list covers everything that tends to drift (light direction, plants, artwork). Ask for contact shadows explicitly or the new sofa floats.$w$,
  'curated',
  ARRAY['image-edit', 'interior', 'furniture', 'preserve', 'real-estate', 'product']::text[],
  'gpt-image-2.5',
  'depikt_original',
  'Depikt',
  NULL,
  $n$Pattern drawn from the interior-design examples in the OpenAI prompting guide; prompt text and scene are Depikt's.

SETUP PROMPT: Photorealistic interior photo of a bright living room: a grey fabric sofa against the far wall, a round patterned rug in front of it, a large window on the left with soft daylight, pale oak floor, a tall fiddle-leaf fig plant in the corner, a small walnut side table with a ceramic lamp, one framed abstract print on the wall. Eye-level, wide-angle but undistorted, 3:2 landscape. No people, no text.$n$,
  'approved',
  true,
  false,
  true,
  'edit_source',
  $r$Check the plant and the framed print against the source. New sofa and rug as specified, in place, correctly lit; everything else unchanged.
Outcome: Pass on attempt 1 (Sunburst high). Oatmeal bouclé sofa on oak legs in the original footprint; navy-and-cream striped flat-weave rug in place; walls, window light, plant, lamp, side table, artwork and coffee table unchanged; contact shadows correct.
Model used: sunburst; attempts: 1.
Success: New sofa and rug as specified, in place, correctly lit; everything else unchanged.
Likely failure: Wall colour, plant or artwork changes; sofa floats without shadow; window light flips.
Check first: Check the plant and the framed print against the source.
Attempts: 2. Model: sunburst.
Reference inputs: A living-room photo, generated with the setup prompt.$r$,
  1,
  '/library/images-2-5/living-room-furniture-swap.webp',
  '2026-09-10T03:00:00.000Z',
  '2026-09-10T03:00:00.000Z'
) ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, title = EXCLUDED.title, category = EXCLUDED.category,
  user_input = EXCLUDED.user_input, prompt = EXCLUDED.prompt, why_it_works = EXCLUDED.why_it_works,
  tags = EXCLUDED.tags, target_model = EXCLUDED.target_model, source_type = EXCLUDED.source_type,
  source_creator = EXCLUDED.source_creator, source_url = EXCLUDED.source_url,
  source_notes = EXCLUDED.source_notes, status = EXCLUDED.status,
  generation_ready = EXCLUDED.generation_ready, gallery_ready = EXCLUDED.gallery_ready,
  needs_reference_images = EXCLUDED.needs_reference_images, reference_mode = EXCLUDED.reference_mode,
  review_notes = EXCLUDED.review_notes, result_count = EXCLUDED.result_count,
  thumbnail_url = EXCLUDED.thumbnail_url, updated_at = now();

-- 14. Texture-Preserving Skin Retouch
INSERT INTO public.curated_prompts (
  id, slug, title, category, user_input, prompt, why_it_works, source, tags, target_model,
  source_type, source_creator, source_url, source_notes, status, generation_ready, gallery_ready,
  needs_reference_images, reference_mode, review_notes, result_count, thumbnail_url, created_at, updated_at
) VALUES (
  'images25-texture-preserving-skin-retouch',
  'texture-preserving-skin-retouch',
  'Texture-Preserving Skin Retouch',
  'Image Edits',
  $input$Professional retouch that removes blemishes but keeps real skin$input$,
  $p$Retouch the attached portrait the way a magazine retoucher would, not the way a beauty filter would.

Remove: temporary blemishes, the small spot on the cheek, minor redness, stray flyaway hairs crossing the face.

Keep: all skin texture (pores, fine lines, the natural sheen on the nose and forehead), freckles, the shape of every feature, the eye colour, the catchlights, the original lighting and colour balance. Do not slim the face, enlarge the eyes, whiten the teeth beyond their natural tone, or smooth the skin into plastic.

Even out the skin tone very gently. The result should look like the same photo on a better day.$p$,
  $w$The line between retouching and a filter is texture, so the prompt names what to remove and, in more detail, what to keep. Listing the classic filter moves (slimming, eye enlargement, plastic skin) as forbidden is what stops them. "The same photo on a better day" is a useful summary the model responds to.$w$,
  'curated',
  ARRAY['image-edit', 'retouch', 'portrait', 'skin', 'preserve', 'beauty']::text[],
  'gpt-image-2.5',
  'depikt_original',
  'Depikt',
  NULL,
  $n$Depikt original.

SETUP PROMPT: Photorealistic close-up portrait of a man in his late thirties, head and shoulders, neutral expression with a slight smile, natural window light from the left, visible pores and fine lines, a few freckles across the nose, one small blemish on the right cheek, slight redness around the nose, a few flyaway hairs. Plain warm-grey background, 85mm lens look, 4:5 portrait. No text.$n$,
  'approved',
  true,
  false,
  true,
  'edit_source',
  $r$Zoom on the nose and cheek for pore texture. Blemish and redness gone; pores, freckles and lines intact; features and lighting unchanged.
Outcome: Pass on attempt 1 (Sunburst high). Cheek blemish and nose redness removed, flyaways tidied; pores, forehead lines, freckles, stubble and catchlights intact; features, colour balance and lighting unchanged; no plastic smoothing.
Model used: sunburst; attempts: 1.
Success: Blemish and redness gone; pores, freckles and lines intact; features and lighting unchanged.
Likely failure: Plastic smoothing; face reshaped; freckles removed.
Check first: Zoom on the nose and cheek for pore texture.
Attempts: 2. Model: sunburst.
Reference inputs: A close-up portrait with visible skin texture, generated with the setup prompt.$r$,
  1,
  '/library/images-2-5/texture-preserving-skin-retouch.webp',
  '2026-09-10T03:00:00.000Z',
  '2026-09-10T03:00:00.000Z'
) ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, title = EXCLUDED.title, category = EXCLUDED.category,
  user_input = EXCLUDED.user_input, prompt = EXCLUDED.prompt, why_it_works = EXCLUDED.why_it_works,
  tags = EXCLUDED.tags, target_model = EXCLUDED.target_model, source_type = EXCLUDED.source_type,
  source_creator = EXCLUDED.source_creator, source_url = EXCLUDED.source_url,
  source_notes = EXCLUDED.source_notes, status = EXCLUDED.status,
  generation_ready = EXCLUDED.generation_ready, gallery_ready = EXCLUDED.gallery_ready,
  needs_reference_images = EXCLUDED.needs_reference_images, reference_mode = EXCLUDED.reference_mode,
  review_notes = EXCLUDED.review_notes, result_count = EXCLUDED.result_count,
  thumbnail_url = EXCLUDED.thumbnail_url, updated_at = now();

-- 15. Old Photo Restoration and Colorization
INSERT INTO public.curated_prompts (
  id, slug, title, category, user_input, prompt, why_it_works, source, tags, target_model,
  source_type, source_creator, source_url, source_notes, status, generation_ready, gallery_ready,
  needs_reference_images, reference_mode, review_notes, result_count, thumbnail_url, created_at, updated_at
) VALUES (
  'images25-old-photo-restoration-colorize',
  'old-photo-restoration-colorize',
  'Old Photo Restoration and Colorization',
  'Image Edits',
  $input$Repair a creased, faded family photo and colourise it plausibly$input$,
  $p$Restore the attached old photograph in two layers of work.

Repair: remove the creases, tears, water stain and dust; rebuild the missing corner using the surrounding content; recover contrast and detail in the faded areas. Keep every face, pose, garment and background object exactly as in the original; do not reinterpret expressions or add anything that was not there.

Colourise: period-plausible, restrained colours for the 1950s: muted fabric tones, natural skin, a soft blue sky, no oversaturation. Keep the light grain of the original so it still reads as a photograph of its time, not a modern render.

Output the photo alone, straightened, without the paper border.$p$,
  $w$Restoration is two jobs, and separating them keeps the model honest: repair with strict preservation, then colour with a period brief. "Do not reinterpret expressions" matters because the model will otherwise improve faces. Keeping grain is the difference between restored and fake.$w$,
  'curated',
  ARRAY['image-edit', 'restoration', 'colorize', 'vintage', 'family', 'preserve']::text[],
  'gpt-image-2.5',
  'depikt_original',
  'Depikt',
  NULL,
  $n$Depikt original; the setup image creates the damaged source so no real family photo is needed for testing.

SETUP PROMPT: Scan of a damaged black-and-white family photograph from the 1950s: a family of four in front of a suburban house next to a parked car, parents standing, two children in front, everyone smiling at the camera. The print is faded and low-contrast, with two deep creases crossing the image, a torn-off bottom-left corner, a brown water stain top-right, scattered dust and scratches, and a scalloped white paper border. Slightly skewed on the scanner. 5:4 landscape. No text.$n$,
  'approved',
  true,
  true,
  true,
  'edit_source',
  $r$Compare each face and the car to the source. Damage gone, corner rebuilt, faces identical, plausible muted colour, grain kept.
Outcome: Pass on attempt 1 (Sunburst high). Creases, stain, dust and the torn corner repaired; straightened; paper border removed; all four faces, poses and the car unchanged; restrained 1950s colour with grain kept.
Model used: sunburst; attempts: 1.
Success: Damage gone, corner rebuilt, faces identical, plausible muted colour, grain kept.
Likely failure: Faces changed or beautified; saturated colours; new objects added.
Check first: Compare each face and the car to the source.
Attempts: 2. Model: sunburst.
Reference inputs: A scan of a damaged black-and-white photo, generated with the setup prompt.$r$,
  1,
  '/library/images-2-5/old-photo-restoration-colorize.webp',
  '2026-09-10T03:00:00.000Z',
  '2026-09-10T03:00:00.000Z'
) ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, title = EXCLUDED.title, category = EXCLUDED.category,
  user_input = EXCLUDED.user_input, prompt = EXCLUDED.prompt, why_it_works = EXCLUDED.why_it_works,
  tags = EXCLUDED.tags, target_model = EXCLUDED.target_model, source_type = EXCLUDED.source_type,
  source_creator = EXCLUDED.source_creator, source_url = EXCLUDED.source_url,
  source_notes = EXCLUDED.source_notes, status = EXCLUDED.status,
  generation_ready = EXCLUDED.generation_ready, gallery_ready = EXCLUDED.gallery_ready,
  needs_reference_images = EXCLUDED.needs_reference_images, reference_mode = EXCLUDED.reference_mode,
  review_notes = EXCLUDED.review_notes, result_count = EXCLUDED.result_count,
  thumbnail_url = EXCLUDED.thumbnail_url, updated_at = now();

-- 16. Casual Photo to Studio Headshot
INSERT INTO public.curated_prompts (
  id, slug, title, category, user_input, prompt, why_it_works, source, tags, target_model,
  source_type, source_creator, source_url, source_notes, status, generation_ready, gallery_ready,
  needs_reference_images, reference_mode, review_notes, result_count, thumbnail_url, created_at, updated_at
) VALUES (
  'images25-casual-photo-to-studio-headshot',
  'casual-photo-to-studio-headshot',
  'Casual Photo to Studio Headshot',
  'Image Edits',
  $input$Turn a casual full-body photo into a professional headshot without changing the person$input$,
  $p$From the attached casual photo, produce a professional studio headshot of the same person.

Identity is locked: same face, hair, skin tone, eye colour, eyebrows, smile and ears. Do not slim, smooth or age them.

Change: crop to head-and-shoulders with the eyes on the upper third; replace the outfit with a plain navy crew-neck knit; replace the background with a soft mid-grey seamless with a gentle vignette; light with a large soft key from the front-left, subtle fill and a faint hair light so the hair separates from the background. Slight shallow depth of field, 85mm look, natural colour.

Straight-on pose, relaxed shoulders, direct eye contact. No text, no logo.$p$,
  $w$Headshots from casual photos are the everyday use of identity preservation. The prompt names the identity anchors, then lists the four things a studio changes (crop, outfit, backdrop, light) so the model knows the scope. Specifying the light setup by position beats "professional lighting" every time.$w$,
  'curated',
  ARRAY['image-edit', 'headshot', 'portrait', 'identity-lock', 'linkedin', 'studio']::text[],
  'gpt-image-2.5',
  'depikt_original',
  'Depikt',
  NULL,
  $n$Depikt original.$n$,
  'approved',
  true,
  false,
  true,
  'identity',
  $r$Hair texture and smile against the source. Unmistakably the same person; grey seamless; navy knit; soft studio light; no text.
Outcome: Pass on attempt 1 (Sunburst high). Unmistakably the same person (curls, brows, smile, earrings); head-and-shoulders crop, navy crew-neck knit, mid-grey seamless with vignette, soft front-left key and hair separation; no text.
Model used: sunburst; attempts: 1.
Fixtures: portrait-full
Success: Unmistakably the same person; grey seamless; navy knit; soft studio light; no text.
Likely failure: Face smoothed or reshaped; hair changed; outfit keeps the original tee.
Check first: Hair texture and smile against the source.
Attempts: 2. Model: sunburst.
Reference inputs: A casual photo where the face is clearly visible.$r$,
  1,
  '/library/images-2-5/casual-photo-to-studio-headshot.webp',
  '2026-09-10T03:00:00.000Z',
  '2026-09-10T03:00:00.000Z'
) ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, title = EXCLUDED.title, category = EXCLUDED.category,
  user_input = EXCLUDED.user_input, prompt = EXCLUDED.prompt, why_it_works = EXCLUDED.why_it_works,
  tags = EXCLUDED.tags, target_model = EXCLUDED.target_model, source_type = EXCLUDED.source_type,
  source_creator = EXCLUDED.source_creator, source_url = EXCLUDED.source_url,
  source_notes = EXCLUDED.source_notes, status = EXCLUDED.status,
  generation_ready = EXCLUDED.generation_ready, gallery_ready = EXCLUDED.gallery_ready,
  needs_reference_images = EXCLUDED.needs_reference_images, reference_mode = EXCLUDED.reference_mode,
  review_notes = EXCLUDED.review_notes, result_count = EXCLUDED.result_count,
  thumbnail_url = EXCLUDED.thumbnail_url, updated_at = now();

-- 17. App Icon Set, One System
INSERT INTO public.curated_prompts (
  id, slug, title, category, user_input, prompt, why_it_works, source, tags, target_model,
  source_type, source_creator, source_url, source_notes, status, generation_ready, gallery_ready,
  needs_reference_images, reference_mode, review_notes, result_count, thumbnail_url, created_at, updated_at
) VALUES (
  'images25-app-icon-set-six',
  'app-icon-set-six',
  'App Icon Set, One System',
  'UI Mockups',
  $input$Six app icons that share one visual system, presented on a grid$input$,
  $p$Design a set of six app icons for a fictional productivity suite, shown on one presentation board.

System: rounded-square iOS-style icons, identical corner radius, each with a single flat white glyph centred on a two-tone background (one base colour plus a slightly darker diagonal split in the lower-right). Same glyph stroke weight across all six. No text, no letters as glyphs.

The six, left to right in two rows of three, each with its base colour: Notes (paper sheet glyph, warm yellow), Calendar (grid glyph, coral red), Tasks (check circle glyph, leaf green), Timer (stopwatch glyph, indigo), Files (folder glyph, sky blue), Mail (envelope glyph, slate grey).

Present them at equal size on a plain off-white board with even spacing and a soft contact shadow under each. Nothing else on the board.$p$,
  $w$Icon sets drift when each icon is designed alone, so the prompt defines the system once (shape, radius, glyph treatment, split, stroke) and then only varies the glyph and base colour per icon. Forbidding letters as glyphs removes the one element that would break. The board layout makes consistency easy to judge.$w$,
  'curated',
  ARRAY['ui', 'app-icon', 'icon-set', 'design-system', 'branding', 'mockup']::text[],
  'gpt-image-2.5',
  'depikt_original',
  'Depikt',
  NULL,
  $n$Depikt original.$n$,
  'approved',
  true,
  true,
  false,
  'none',
  $r$Compare the corner radius of icon 1 and icon 6. Six icons with identical geometry and stroke; six named glyphs and colours; no text.
Outcome: Pass on attempt 1 (Sunburst high). Six rounded squares with identical radius, white glyphs of one stroke weight, two-tone diagonal split; Notes, Calendar, Tasks, Timer, Files, Mail in the stated colours; no letters used as glyphs; soft contact shadows on an off-white board.
Model used: sunburst; attempts: 1.
Success: Six icons with identical geometry and stroke; six named glyphs and colours; no text.
Likely failure: Different corner radii or stroke weights; a letter used as a glyph; extra labels.
Check first: Compare the corner radius of icon 1 and icon 6.
Attempts: 1. Model: sunburst.$r$,
  1,
  '/library/images-2-5/app-icon-set-six.webp',
  '2026-09-10T03:00:00.000Z',
  '2026-09-10T03:00:00.000Z'
) ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, title = EXCLUDED.title, category = EXCLUDED.category,
  user_input = EXCLUDED.user_input, prompt = EXCLUDED.prompt, why_it_works = EXCLUDED.why_it_works,
  tags = EXCLUDED.tags, target_model = EXCLUDED.target_model, source_type = EXCLUDED.source_type,
  source_creator = EXCLUDED.source_creator, source_url = EXCLUDED.source_url,
  source_notes = EXCLUDED.source_notes, status = EXCLUDED.status,
  generation_ready = EXCLUDED.generation_ready, gallery_ready = EXCLUDED.gallery_ready,
  needs_reference_images = EXCLUDED.needs_reference_images, reference_mode = EXCLUDED.reference_mode,
  review_notes = EXCLUDED.review_notes, result_count = EXCLUDED.result_count,
  thumbnail_url = EXCLUDED.thumbnail_url, updated_at = now();

-- 18. YouTube Thumbnail with Exact Title
INSERT INTO public.curated_prompts (
  id, slug, title, category, user_input, prompt, why_it_works, source, tags, target_model,
  source_type, source_creator, source_url, source_notes, status, generation_ready, gallery_ready,
  needs_reference_images, reference_mode, review_notes, result_count, thumbnail_url, created_at, updated_at
) VALUES (
  'images25-youtube-thumbnail-exact-title',
  'youtube-thumbnail-exact-title',
  'YouTube Thumbnail with Exact Title',
  'Social Posts',
  $input$16:9 thumbnail with a big exact title and a clear focal object$input$,
  $p$Create a 16:9 YouTube thumbnail.

Left 60%: the text "I TESTED 5 STANDING DESKS" in a very heavy condensed sans, three stacked lines, white with a thick black outline and a subtle drop shadow, filling the height. Beneath it, smaller, in bright yellow: "one was a mistake".

Right 40%: a photorealistic standing desk at its highest position, slightly tilted toward the camera, with a red circle-and-slash icon drawn over one of its legs. Background: a clean studio wall in deep teal with a soft spotlight behind the desk.

High contrast, no other text, no faces, no logos. Everything must read at 320 pixels wide.$p$,
  $w$Thumbnails are a legibility problem, so the prompt allocates space (60/40), quotes the two strings, specifies weight, outline and colour, and sets a pixel target. A single focal object with one graphic overlay reads faster than a busy scene. Change the strings and the object; keep the layout.$w$,
  'curated',
  ARRAY['social', 'youtube', 'thumbnail', 'exact-text', 'typography', '16:9']::text[],
  'gpt-image-2.5',
  'depikt_original',
  'Depikt',
  NULL,
  $n$Depikt original.$n$,
  'approved',
  true,
  false,
  false,
  'none',
  $r$Shrink to 320px and read the title. Both strings exact and huge; desk on the right; teal background; legible when small.
Outcome: Pass on attempt 1 (Sunburst high). Both strings exact: three-line white outlined title on the left, yellow 'one was a mistake' beneath; standing desk with red circle-and-slash on the right; deep teal studio wall; legible at small size; no other text.
Model used: sunburst; attempts: 1.
Success: Both strings exact and huge; desk on the right; teal background; legible when small.
Likely failure: Extra words; title wraps badly; desk too small to read.
Check first: Shrink to 320px and read the title.
Attempts: 2. Model: sunburst.$r$,
  1,
  '/library/images-2-5/youtube-thumbnail-exact-title.webp',
  '2026-09-10T03:00:00.000Z',
  '2026-09-10T03:00:00.000Z'
) ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, title = EXCLUDED.title, category = EXCLUDED.category,
  user_input = EXCLUDED.user_input, prompt = EXCLUDED.prompt, why_it_works = EXCLUDED.why_it_works,
  tags = EXCLUDED.tags, target_model = EXCLUDED.target_model, source_type = EXCLUDED.source_type,
  source_creator = EXCLUDED.source_creator, source_url = EXCLUDED.source_url,
  source_notes = EXCLUDED.source_notes, status = EXCLUDED.status,
  generation_ready = EXCLUDED.generation_ready, gallery_ready = EXCLUDED.gallery_ready,
  needs_reference_images = EXCLUDED.needs_reference_images, reference_mode = EXCLUDED.reference_mode,
  review_notes = EXCLUDED.review_notes, result_count = EXCLUDED.result_count,
  thumbnail_url = EXCLUDED.thumbnail_url, updated_at = now();

-- 19. Holiday Card with Exact Greeting
INSERT INTO public.curated_prompts (
  id, slug, title, category, user_input, prompt, why_it_works, source, tags, target_model,
  source_type, source_creator, source_url, source_notes, status, generation_ready, gallery_ready,
  needs_reference_images, reference_mode, review_notes, result_count, thumbnail_url, created_at, updated_at
) VALUES (
  'images25-holiday-card-exact-greeting',
  'holiday-card-exact-greeting',
  'Holiday Card with Exact Greeting',
  'Posters',
  $input$Printable 5x7 holiday card with a hand-lettered exact greeting$input$,
  $p$Design the front of a 5 x 7 portrait holiday card.

Illustration: a cosy winter scene in a warm gouache style, a small red cottage in deep snow at dusk, warm light in every window, a string of lights across the porch, pine trees behind, big soft snowflakes falling. Limited palette of cream, deep green, warm red and gold.

Greeting, exactly, in hand-lettered brush script in cream across the sky area: "Warm wishes from our home to yours". Nothing else written anywhere on the card.

Leave a quarter-inch clean margin for print bleed. No border line, no year, no names.$p$,
  $w$Cards need one illustration and one line of text that the printer will not have to fix. Quoting the greeting, naming the lettering style and placing it in the sky (where there is no detail to collide with) keeps it clean. The explicit "no year, no names" stops the model helpfully adding both.$w$,
  'curated',
  ARRAY['poster', 'holiday-card', 'greeting', 'exact-text', 'gouache', 'print']::text[],
  'gpt-image-2.5',
  'depikt_original',
  'Depikt',
  NULL,
  $n$Depikt original.$n$,
  'approved',
  true,
  true,
  false,
  'none',
  $r$Read the greeting word by word. Greeting exact in brush script, in the sky; gouache cottage scene; nothing else written.
Outcome: Pass on attempt 1 (Sunburst high). Greeting exact in cream brush script placed in the sky; gouache red cottage at dusk with lit windows, porch lights, pines and falling snow; limited palette; no year, names or border line.
Model used: sunburst; attempts: 1.
Success: Greeting exact in brush script, in the sky; gouache cottage scene; nothing else written.
Likely failure: Extra text (a year, a name); greeting misspelled; lettering overlapping the cottage.
Check first: Read the greeting word by word.
Attempts: 2. Model: sunburst.$r$,
  1,
  '/library/images-2-5/holiday-card-exact-greeting.webp',
  '2026-09-10T03:00:00.000Z',
  '2026-09-10T03:00:00.000Z'
) ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, title = EXCLUDED.title, category = EXCLUDED.category,
  user_input = EXCLUDED.user_input, prompt = EXCLUDED.prompt, why_it_works = EXCLUDED.why_it_works,
  tags = EXCLUDED.tags, target_model = EXCLUDED.target_model, source_type = EXCLUDED.source_type,
  source_creator = EXCLUDED.source_creator, source_url = EXCLUDED.source_url,
  source_notes = EXCLUDED.source_notes, status = EXCLUDED.status,
  generation_ready = EXCLUDED.generation_ready, gallery_ready = EXCLUDED.gallery_ready,
  needs_reference_images = EXCLUDED.needs_reference_images, reference_mode = EXCLUDED.reference_mode,
  review_notes = EXCLUDED.review_notes, result_count = EXCLUDED.result_count,
  thumbnail_url = EXCLUDED.thumbnail_url, updated_at = now();

-- 20. Certificate Template with Exact Names
INSERT INTO public.curated_prompts (
  id, slug, title, category, user_input, prompt, why_it_works, source, tags, target_model,
  source_type, source_creator, source_url, source_notes, status, generation_ready, gallery_ready,
  needs_reference_images, reference_mode, review_notes, result_count, thumbnail_url, created_at, updated_at
) VALUES (
  'images25-certificate-template-exact-names',
  'certificate-template-exact-names',
  'Certificate Template with Exact Names',
  'Posters',
  $input$Landscape certificate with exact recipient, course and date text$input$,
  $p$Design a landscape certificate of completion on cream paper with a fine navy and gold guilloche border.

Text, top to bottom, all centred, exactly as written:
"CERTIFICATE OF COMPLETION" (small caps, letter-spaced, navy)
"This certifies that" (small italic serif)
"Maya Okonkwo" (large elegant script, gold)
"has successfully completed the course" (small italic serif)
"Foundations of Visual Design" (bold serif, navy)
"12 September 2026" (small serif)

Bottom-left, a signature line with "Course Director" beneath it. Bottom-right, an embossed gold circular seal with a laurel motif and no text inside. Balanced whitespace, nothing else on the page.$p$,
  $w$Certificates are pure exact-text work: six strings, each with a role and a type treatment. Listing them in order with their styles is far more reliable than describing the document. The seal is told to carry no text because seals are where invented letters appear. Swap the three variable lines for any recipient.$w$,
  'curated',
  ARRAY['poster', 'certificate', 'exact-text', 'typography', 'document', 'print']::text[],
  'gpt-image-2.5',
  'depikt_original',
  'Depikt',
  NULL,
  $n$Depikt original.$n$,
  'approved',
  true,
  false,
  false,
  'none',
  $r$Read the name and the date. All six strings letter-perfect in the stated styles; seal with no text; clean border.
Outcome: Pass on attempt 1 (Sunburst high). All six strings letter-perfect in the stated treatments (letter-spaced small caps, italic serif, gold script name, bold serif course, date); guilloche navy-and-gold border; signature line with 'Course Director'; embossed gold laurel seal with no text; nothing else on the page.
Model used: sunburst; attempts: 1.
Success: All six strings letter-perfect in the stated styles; seal with no text; clean border.
Likely failure: A string altered; text inside the seal; a misspelled name.
Check first: Read the name and the date.
Attempts: 2. Model: sunburst.$r$,
  1,
  '/library/images-2-5/certificate-template-exact-names.webp',
  '2026-09-10T03:00:00.000Z',
  '2026-09-10T03:00:00.000Z'
) ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, title = EXCLUDED.title, category = EXCLUDED.category,
  user_input = EXCLUDED.user_input, prompt = EXCLUDED.prompt, why_it_works = EXCLUDED.why_it_works,
  tags = EXCLUDED.tags, target_model = EXCLUDED.target_model, source_type = EXCLUDED.source_type,
  source_creator = EXCLUDED.source_creator, source_url = EXCLUDED.source_url,
  source_notes = EXCLUDED.source_notes, status = EXCLUDED.status,
  generation_ready = EXCLUDED.generation_ready, gallery_ready = EXCLUDED.gallery_ready,
  needs_reference_images = EXCLUDED.needs_reference_images, reference_mode = EXCLUDED.reference_mode,
  review_notes = EXCLUDED.review_notes, result_count = EXCLUDED.result_count,
  thumbnail_url = EXCLUDED.thumbnail_url, updated_at = now();
