/**
 * export-staged-images-2-5.ts
 *
 * Writes supabase/insert-images-2-5-batch1-staged.sql from the staged
 * Images 2.5 records in src/data/images-2-5-staged.ts.
 *
 * Rows insert with their current status; the public library shows only
 * status = 'approved'. thumbnail_url points at /library/images-2-5/<slug>.webp,
 * served from public/ (move to Supabase Storage if the gallery pipeline needs it).
 * Promotion = edit the record's status in the TS file, re-run this script,
 * re-run the SQL (ON CONFLICT DO UPDATE), then node scripts/sync-curated-prompts.mjs.
 *
 * Usage: node scripts/export-staged-images-2-5.ts [--all]
 * Default: only status = 'approved' rows (Supabase holds the approved library;
 * staging holds work in progress). --all also exports held records.
 * The provenance migration (20260909120000) is already applied in production.
 */

import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { stagedImages25Prompts } from "../src/data/images-2-5-staged.ts";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = resolve(ROOT, "supabase/insert-images-2-5-batch1-staged.sql");

/** Dollar-quote with a tag that cannot appear in the text. */
function dq(tag: string, value: string | null | undefined): string {
  if (value == null) return "NULL";
  let t = tag;
  while (value.includes(`$${t}$`)) t += "x";
  return `$${t}$${value}$${t}$`;
}
function lit(value: string | null | undefined): string {
  if (value == null) return "NULL";
  return `'${value.replace(/'/g, "''")}'`;
}
function arr(values: string[]): string {
  return `ARRAY[${values.map(lit).join(", ")}]::text[]`;
}

const exportAll = process.argv.includes("--all");
const rows = stagedImages25Prompts.filter((p) => exportAll || p.status === "approved");

const statements = rows.map((p, i) => {
  const notes = [p.source_notes, p.setup_prompt ? `SETUP PROMPT: ${p.setup_prompt}` : null]
    .filter(Boolean)
    .join("\n\n");
  const review = [
    p.review_notes,
    p.outcome_notes ? `Outcome: ${p.outcome_notes}` : null,
    p.model_used ? `Model used: ${p.model_used}; attempts: ${p.attempts ?? 0}.` : null,
    p.fixtures_used?.length ? `Fixtures: ${p.fixtures_used.join(", ")}` : null,
    `Success: ${p.review.success}`,
    `Likely failure: ${p.review.failure}`,
    `Check first: ${p.review.check_first}`,
    `Attempts: ${p.review.attempts}. Model: ${p.review.model_hint}.`,
    p.reference_inputs?.length ? `Reference inputs: ${p.reference_inputs.join(" | ")}` : null,
  ]
    .filter(Boolean)
    .join("\n");
  return `-- ${i + 1}. ${p.title}
INSERT INTO public.curated_prompts (
  id, slug, title, category, user_input, prompt, why_it_works, source, tags, target_model,
  source_type, source_creator, source_url, source_notes, status, generation_ready, gallery_ready,
  needs_reference_images, reference_mode, review_notes, result_count, thumbnail_url, created_at, updated_at
) VALUES (
  ${lit(p.id)},
  ${lit(p.slug)},
  ${lit(p.title)},
  ${lit(p.category)},
  ${dq("input", p.user_input)},
  ${dq("p", p.prompt)},
  ${dq("w", p.why_it_works)},
  'curated',
  ${arr(p.tags)},
  'gpt-image-2.5',
  ${lit(p.source_type)},
  ${lit(p.source_creator)},
  ${lit(p.source_url)},
  ${dq("n", notes)},
  ${lit(p.status)},
  ${p.generation_ready},
  ${p.gallery_ready},
  ${p.needs_reference_images},
  ${lit(p.reference_mode)},
  ${dq("r", review)},
  ${p.result_count},
  ${lit(p.thumbnail_url ?? null)},
  ${lit(p.created_at)},
  ${lit(p.updated_at)}
) ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, title = EXCLUDED.title, category = EXCLUDED.category,
  user_input = EXCLUDED.user_input, prompt = EXCLUDED.prompt, why_it_works = EXCLUDED.why_it_works,
  tags = EXCLUDED.tags, target_model = EXCLUDED.target_model, source_type = EXCLUDED.source_type,
  source_creator = EXCLUDED.source_creator, source_url = EXCLUDED.source_url,
  source_notes = EXCLUDED.source_notes, status = EXCLUDED.status,
  generation_ready = EXCLUDED.generation_ready, gallery_ready = EXCLUDED.gallery_ready,
  needs_reference_images = EXCLUDED.needs_reference_images, reference_mode = EXCLUDED.reference_mode,
  review_notes = EXCLUDED.review_notes, result_count = EXCLUDED.result_count,
  thumbnail_url = EXCLUDED.thumbnail_url, updated_at = now();
`;
});

const byStatus = new Map<string, number>();
for (const p of rows) byStatus.set(p.status, (byStatus.get(p.status) ?? 0) + 1);

const header = `-- ChatGPT Images 2.5 collection, batch 1 (${rows.length} of ${stagedImages25Prompts.length} staged records${exportAll ? "" : ", approved only"})
-- Generated by scripts/export-staged-images-2-5.ts — do not edit by hand.
-- Assumes migration 20260909120000 (provenance columns) is already applied; do not re-run it.
-- Idempotent upsert (ON CONFLICT DO UPDATE). The public library shows only status = 'approved'.
-- Status counts: ${[...byStatus.entries()].map(([k, v]) => `${k}=${v}`).join(", ")}.

`;

writeFileSync(OUT, header + statements.join("\n"));
console.log(
  `Wrote ${OUT} (${rows.length} rows${exportAll ? ", all statuses" : ", approved only"})`,
);
