/**
 * export-og-urls.mjs
 * Exports all non-null thumbnail_url values from curated_prompts
 * and writes src/data/og-thumbnails.ts.
 * Usage: node scripts/export-og-urls.mjs
 */

import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { createClient } from "@supabase/supabase-js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const OUT_FILE = resolve(ROOT, "src/data/og-thumbnails.ts");

// Load .env
const envFile = readFileSync(resolve(ROOT, ".env"), "utf8");
const env = Object.fromEntries(
  envFile
    .split("\n")
    .filter((l) => l && !l.startsWith("#"))
    .map((l) => {
      const eq = l.indexOf("=");
      return [l.slice(0, eq), l.slice(eq + 1).replace(/^["']|["']$/g, "")];
    })
);

const supabase = createClient(
  env.SUPABASE_URL || env.VITE_SUPABASE_URL,
  env.SUPABASE_SERVICE_ROLE_KEY || env.SUPABASE_PUBLISHABLE_KEY || env.VITE_SUPABASE_PUBLISHABLE_KEY
);

// Fetch all non-null thumbnail URLs
const { data, error } = await supabase
  .from("curated_prompts")
  .select("thumbnail_url")
  .not("thumbnail_url", "is", null)
  .order("created_at", { ascending: true });

if (error) {
  console.error("Failed to fetch:", error.message);
  process.exit(1);
}

const urls = data.map((row) => row.thumbnail_url);

const ts = `/**
 * ${urls.length} curated prompt thumbnail URLs for OG images.
 * Auto-generated by scripts/export-og-urls.mjs — do not edit manually.
 */

export const OG_THUMBNAIL_URLS: string[] = [
${urls.map((u) => `  "${u}",`).join("\n")}
];
`;

writeFileSync(OUT_FILE, ts, "utf8");
console.log(`Exported ${urls.length} thumbnail URLs to ${OUT_FILE}`);
