/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PromptRouteImport } from './routes/prompt'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CritiqueRouteImport } from './routes/critique'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as IntegrationsMcpRouteImport } from './routes/integrations.mcp'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ApiPublicGeneratePromptRouteImport } from './routes/api/public/generate-prompt'
import { Route as ApiPublicCritiquePromptRouteImport } from './routes/api/public/critique-prompt'
import { Route as ApiBlogRssDotxmlRouteImport } from './routes/api/blog.rss[.]xml'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptRoute = PromptRouteImport.update({
  id: '/prompt',
  path: '/prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CritiqueRoute = CritiqueRouteImport.update({
  id: '/critique',
  path: '/critique',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsMcpRoute = IntegrationsMcpRouteImport.update({
  id: '/integrations/mcp',
  path: '/integrations/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGeneratePromptRoute = ApiPublicGeneratePromptRouteImport.update({
  id: '/api/public/generate-prompt',
  path: '/api/public/generate-prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCritiquePromptRoute = ApiPublicCritiquePromptRouteImport.update({
  id: '/api/public/critique-prompt',
  path: '/api/public/critique-prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogRssDotxmlRoute = ApiBlogRssDotxmlRouteImport.update({
  id: '/api/blog/rss.xml',
  path: '/api/blog/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/critique': typeof CritiqueRoute
  '/gallery': typeof GalleryRoute
  '/generate': typeof GenerateRoute
  '/library': typeof LibraryRoute
  '/mcp': typeof McpRoute
  '/prompt': typeof PromptRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/integrations/mcp': typeof IntegrationsMcpRoute
  '/blog/': typeof BlogIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/api/blog/rss.xml': typeof ApiBlogRssDotxmlRoute
  '/api/public/critique-prompt': typeof ApiPublicCritiquePromptRoute
  '/api/public/generate-prompt': typeof ApiPublicGeneratePromptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/critique': typeof CritiqueRoute
  '/gallery': typeof GalleryRoute
  '/generate': typeof GenerateRoute
  '/library': typeof LibraryRoute
  '/mcp': typeof McpRoute
  '/prompt': typeof PromptRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/integrations/mcp': typeof IntegrationsMcpRoute
  '/blog': typeof BlogIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/api/blog/rss.xml': typeof ApiBlogRssDotxmlRoute
  '/api/public/critique-prompt': typeof ApiPublicCritiquePromptRoute
  '/api/public/generate-prompt': typeof ApiPublicGeneratePromptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/critique': typeof CritiqueRoute
  '/gallery': typeof GalleryRoute
  '/generate': typeof GenerateRoute
  '/library': typeof LibraryRoute
  '/mcp': typeof McpRoute
  '/prompt': typeof PromptRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/integrations/mcp': typeof IntegrationsMcpRoute
  '/blog/': typeof BlogIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/api/blog/rss.xml': typeof ApiBlogRssDotxmlRoute
  '/api/public/critique-prompt': typeof ApiPublicCritiquePromptRoute
  '/api/public/generate-prompt': typeof ApiPublicGeneratePromptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/critique'
    | '/gallery'
    | '/generate'
    | '/library'
    | '/mcp'
    | '/prompt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/integrations/mcp'
    | '/blog/'
    | '/templates/'
    | '/api/blog/rss.xml'
    | '/api/public/critique-prompt'
    | '/api/public/generate-prompt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/critique'
    | '/gallery'
    | '/generate'
    | '/library'
    | '/mcp'
    | '/prompt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/integrations/mcp'
    | '/blog'
    | '/templates'
    | '/api/blog/rss.xml'
    | '/api/public/critique-prompt'
    | '/api/public/generate-prompt'
  id:
    | '__root__'
    | '/'
    | '/critique'
    | '/gallery'
    | '/generate'
    | '/library'
    | '/mcp'
    | '/prompt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/integrations/mcp'
    | '/blog/'
    | '/templates/'
    | '/api/blog/rss.xml'
    | '/api/public/critique-prompt'
    | '/api/public/generate-prompt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CritiqueRoute: typeof CritiqueRoute
  GalleryRoute: typeof GalleryRoute
  GenerateRoute: typeof GenerateRoute
  LibraryRoute: typeof LibraryRoute
  McpRoute: typeof McpRoute
  PromptRoute: typeof PromptRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BlogSlugRoute: typeof BlogSlugRoute
  IntegrationsMcpRoute: typeof IntegrationsMcpRoute
  BlogIndexRoute: typeof BlogIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  ApiBlogRssDotxmlRoute: typeof ApiBlogRssDotxmlRoute
  ApiPublicCritiquePromptRoute: typeof ApiPublicCritiquePromptRoute
  ApiPublicGeneratePromptRoute: typeof ApiPublicGeneratePromptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt': {
      id: '/prompt'
      path: '/prompt'
      fullPath: '/prompt'
      preLoaderRoute: typeof PromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/critique': {
      id: '/critique'
      path: '/critique'
      fullPath: '/critique'
      preLoaderRoute: typeof CritiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/mcp': {
      id: '/integrations/mcp'
      path: '/integrations/mcp'
      fullPath: '/integrations/mcp'
      preLoaderRoute: typeof IntegrationsMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/generate-prompt': {
      id: '/api/public/generate-prompt'
      path: '/api/public/generate-prompt'
      fullPath: '/api/public/generate-prompt'
      preLoaderRoute: typeof ApiPublicGeneratePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/critique-prompt': {
      id: '/api/public/critique-prompt'
      path: '/api/public/critique-prompt'
      fullPath: '/api/public/critique-prompt'
      preLoaderRoute: typeof ApiPublicCritiquePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/rss.xml': {
      id: '/api/blog/rss.xml'
      path: '/api/blog/rss.xml'
      fullPath: '/api/blog/rss.xml'
      preLoaderRoute: typeof ApiBlogRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CritiqueRoute: CritiqueRoute,
  GalleryRoute: GalleryRoute,
  GenerateRoute: GenerateRoute,
  LibraryRoute: LibraryRoute,
  McpRoute: McpRoute,
  PromptRoute: PromptRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BlogSlugRoute: BlogSlugRoute,
  IntegrationsMcpRoute: IntegrationsMcpRoute,
  BlogIndexRoute: BlogIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  ApiBlogRssDotxmlRoute: ApiBlogRssDotxmlRoute,
  ApiPublicCritiquePromptRoute: ApiPublicCritiquePromptRoute,
  ApiPublicGeneratePromptRoute: ApiPublicGeneratePromptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
