/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PromptRouteImport } from './routes/prompt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CritiqueRouteImport } from './routes/critique'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as IntegrationsMcpRouteImport } from './routes/integrations.mcp'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ApiPublicGeneratePromptRouteImport } from './routes/api/public/generate-prompt'
import { Route as ApiPublicCritiquePromptRouteImport } from './routes/api/public/critique-prompt'
import { Route as ApiGenerationReferencesRouteImport } from './routes/api/generation/references'
import { Route as ApiGenerationJobsRouteImport } from './routes/api/generation/jobs'
import { Route as ApiGenerationCreditsRouteImport } from './routes/api/generation/credits'
import { Route as ApiBlogRssDotxmlRouteImport } from './routes/api/blog.rss[.]xml'
import { Route as ApiBillingWebhookRouteImport } from './routes/api/billing/webhook'
import { Route as ApiBillingPortalRouteImport } from './routes/api/billing/portal'
import { Route as ApiBillingConfirmRouteImport } from './routes/api/billing/confirm'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing/checkout'
import { Route as ApiBillingAccountRouteImport } from './routes/api/billing/account'
import { Route as ApiAccountUsernameAvailabilityRouteImport } from './routes/api/account/username-availability'
import { Route as ApiAccountProfileRouteImport } from './routes/api/account/profile'
import { Route as ApiAccountDeleteRouteImport } from './routes/api/account/delete'
import { Route as ApiAccountCreationsRouteImport } from './routes/api/account/creations'
import { Route as ApiGenerationSessionsIdRouteImport } from './routes/api/generation/sessions.$id'
import { Route as ApiGenerationJobsIdRouteImport } from './routes/api/generation/jobs.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptRoute = PromptRouteImport.update({
  id: '/prompt',
  path: '/prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CritiqueRoute = CritiqueRouteImport.update({
  id: '/critique',
  path: '/critique',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsMcpRoute = IntegrationsMcpRouteImport.update({
  id: '/integrations/mcp',
  path: '/integrations/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGeneratePromptRoute = ApiPublicGeneratePromptRouteImport.update({
  id: '/api/public/generate-prompt',
  path: '/api/public/generate-prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCritiquePromptRoute = ApiPublicCritiquePromptRouteImport.update({
  id: '/api/public/critique-prompt',
  path: '/api/public/critique-prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerationReferencesRoute = ApiGenerationReferencesRouteImport.update({
  id: '/api/generation/references',
  path: '/api/generation/references',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerationJobsRoute = ApiGenerationJobsRouteImport.update({
  id: '/api/generation/jobs',
  path: '/api/generation/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerationCreditsRoute = ApiGenerationCreditsRouteImport.update({
  id: '/api/generation/credits',
  path: '/api/generation/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogRssDotxmlRoute = ApiBlogRssDotxmlRouteImport.update({
  id: '/api/blog/rss.xml',
  path: '/api/blog/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPortalRoute = ApiBillingPortalRouteImport.update({
  id: '/api/billing/portal',
  path: '/api/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingConfirmRoute = ApiBillingConfirmRouteImport.update({
  id: '/api/billing/confirm',
  path: '/api/billing/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingAccountRoute = ApiBillingAccountRouteImport.update({
  id: '/api/billing/account',
  path: '/api/billing/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountUsernameAvailabilityRoute =
  ApiAccountUsernameAvailabilityRouteImport.update({
    id: '/api/account/username-availability',
    path: '/api/account/username-availability',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAccountProfileRoute = ApiAccountProfileRouteImport.update({
  id: '/api/account/profile',
  path: '/api/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountDeleteRoute = ApiAccountDeleteRouteImport.update({
  id: '/api/account/delete',
  path: '/api/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountCreationsRoute = ApiAccountCreationsRouteImport.update({
  id: '/api/account/creations',
  path: '/api/account/creations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerationSessionsIdRoute = ApiGenerationSessionsIdRouteImport.update({
  id: '/api/generation/sessions/$id',
  path: '/api/generation/sessions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerationJobsIdRoute = ApiGenerationJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiGenerationJobsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/critique': typeof CritiqueRoute
  '/favorites': typeof FavoritesRoute
  '/gallery': typeof GalleryRoute
  '/generate': typeof GenerateRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/prompt': typeof PromptRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/integrations/mcp': typeof IntegrationsMcpRoute
  '/blog/': typeof BlogIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/api/account/creations': typeof ApiAccountCreationsRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/profile': typeof ApiAccountProfileRoute
  '/api/account/username-availability': typeof ApiAccountUsernameAvailabilityRoute
  '/api/billing/account': typeof ApiBillingAccountRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/confirm': typeof ApiBillingConfirmRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/blog/rss.xml': typeof ApiBlogRssDotxmlRoute
  '/api/generation/credits': typeof ApiGenerationCreditsRoute
  '/api/generation/jobs': typeof ApiGenerationJobsRouteWithChildren
  '/api/generation/references': typeof ApiGenerationReferencesRoute
  '/api/public/critique-prompt': typeof ApiPublicCritiquePromptRoute
  '/api/public/generate-prompt': typeof ApiPublicGeneratePromptRoute
  '/api/generation/jobs/$id': typeof ApiGenerationJobsIdRoute
  '/api/generation/sessions/$id': typeof ApiGenerationSessionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/critique': typeof CritiqueRoute
  '/favorites': typeof FavoritesRoute
  '/gallery': typeof GalleryRoute
  '/generate': typeof GenerateRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/prompt': typeof PromptRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/integrations/mcp': typeof IntegrationsMcpRoute
  '/blog': typeof BlogIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/api/account/creations': typeof ApiAccountCreationsRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/profile': typeof ApiAccountProfileRoute
  '/api/account/username-availability': typeof ApiAccountUsernameAvailabilityRoute
  '/api/billing/account': typeof ApiBillingAccountRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/confirm': typeof ApiBillingConfirmRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/blog/rss.xml': typeof ApiBlogRssDotxmlRoute
  '/api/generation/credits': typeof ApiGenerationCreditsRoute
  '/api/generation/jobs': typeof ApiGenerationJobsRouteWithChildren
  '/api/generation/references': typeof ApiGenerationReferencesRoute
  '/api/public/critique-prompt': typeof ApiPublicCritiquePromptRoute
  '/api/public/generate-prompt': typeof ApiPublicGeneratePromptRoute
  '/api/generation/jobs/$id': typeof ApiGenerationJobsIdRoute
  '/api/generation/sessions/$id': typeof ApiGenerationSessionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/critique': typeof CritiqueRoute
  '/favorites': typeof FavoritesRoute
  '/gallery': typeof GalleryRoute
  '/generate': typeof GenerateRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/prompt': typeof PromptRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/integrations/mcp': typeof IntegrationsMcpRoute
  '/blog/': typeof BlogIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/api/account/creations': typeof ApiAccountCreationsRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/profile': typeof ApiAccountProfileRoute
  '/api/account/username-availability': typeof ApiAccountUsernameAvailabilityRoute
  '/api/billing/account': typeof ApiBillingAccountRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/confirm': typeof ApiBillingConfirmRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/blog/rss.xml': typeof ApiBlogRssDotxmlRoute
  '/api/generation/credits': typeof ApiGenerationCreditsRoute
  '/api/generation/jobs': typeof ApiGenerationJobsRouteWithChildren
  '/api/generation/references': typeof ApiGenerationReferencesRoute
  '/api/public/critique-prompt': typeof ApiPublicCritiquePromptRoute
  '/api/public/generate-prompt': typeof ApiPublicGeneratePromptRoute
  '/api/generation/jobs/$id': typeof ApiGenerationJobsIdRoute
  '/api/generation/sessions/$id': typeof ApiGenerationSessionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/critique'
    | '/favorites'
    | '/gallery'
    | '/generate'
    | '/help'
    | '/history'
    | '/library'
    | '/mcp'
    | '/pricing'
    | '/privacy'
    | '/prompt'
    | '/robots.txt'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/terms'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/integrations/mcp'
    | '/blog/'
    | '/templates/'
    | '/api/account/creations'
    | '/api/account/delete'
    | '/api/account/profile'
    | '/api/account/username-availability'
    | '/api/billing/account'
    | '/api/billing/checkout'
    | '/api/billing/confirm'
    | '/api/billing/portal'
    | '/api/billing/webhook'
    | '/api/blog/rss.xml'
    | '/api/generation/credits'
    | '/api/generation/jobs'
    | '/api/generation/references'
    | '/api/public/critique-prompt'
    | '/api/public/generate-prompt'
    | '/api/generation/jobs/$id'
    | '/api/generation/sessions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/critique'
    | '/favorites'
    | '/gallery'
    | '/generate'
    | '/help'
    | '/history'
    | '/library'
    | '/mcp'
    | '/pricing'
    | '/privacy'
    | '/prompt'
    | '/robots.txt'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/terms'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/integrations/mcp'
    | '/blog'
    | '/templates'
    | '/api/account/creations'
    | '/api/account/delete'
    | '/api/account/profile'
    | '/api/account/username-availability'
    | '/api/billing/account'
    | '/api/billing/checkout'
    | '/api/billing/confirm'
    | '/api/billing/portal'
    | '/api/billing/webhook'
    | '/api/blog/rss.xml'
    | '/api/generation/credits'
    | '/api/generation/jobs'
    | '/api/generation/references'
    | '/api/public/critique-prompt'
    | '/api/public/generate-prompt'
    | '/api/generation/jobs/$id'
    | '/api/generation/sessions/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/critique'
    | '/favorites'
    | '/gallery'
    | '/generate'
    | '/help'
    | '/history'
    | '/library'
    | '/mcp'
    | '/pricing'
    | '/privacy'
    | '/prompt'
    | '/robots.txt'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/terms'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/integrations/mcp'
    | '/blog/'
    | '/templates/'
    | '/api/account/creations'
    | '/api/account/delete'
    | '/api/account/profile'
    | '/api/account/username-availability'
    | '/api/billing/account'
    | '/api/billing/checkout'
    | '/api/billing/confirm'
    | '/api/billing/portal'
    | '/api/billing/webhook'
    | '/api/blog/rss.xml'
    | '/api/generation/credits'
    | '/api/generation/jobs'
    | '/api/generation/references'
    | '/api/public/critique-prompt'
    | '/api/public/generate-prompt'
    | '/api/generation/jobs/$id'
    | '/api/generation/sessions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CritiqueRoute: typeof CritiqueRoute
  FavoritesRoute: typeof FavoritesRoute
  GalleryRoute: typeof GalleryRoute
  GenerateRoute: typeof GenerateRoute
  HelpRoute: typeof HelpRoute
  HistoryRoute: typeof HistoryRoute
  LibraryRoute: typeof LibraryRoute
  McpRoute: typeof McpRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  PromptRoute: typeof PromptRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BlogSlugRoute: typeof BlogSlugRoute
  IntegrationsMcpRoute: typeof IntegrationsMcpRoute
  BlogIndexRoute: typeof BlogIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  ApiAccountCreationsRoute: typeof ApiAccountCreationsRoute
  ApiAccountDeleteRoute: typeof ApiAccountDeleteRoute
  ApiAccountProfileRoute: typeof ApiAccountProfileRoute
  ApiAccountUsernameAvailabilityRoute: typeof ApiAccountUsernameAvailabilityRoute
  ApiBillingAccountRoute: typeof ApiBillingAccountRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingConfirmRoute: typeof ApiBillingConfirmRoute
  ApiBillingPortalRoute: typeof ApiBillingPortalRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
  ApiBlogRssDotxmlRoute: typeof ApiBlogRssDotxmlRoute
  ApiGenerationCreditsRoute: typeof ApiGenerationCreditsRoute
  ApiGenerationJobsRoute: typeof ApiGenerationJobsRouteWithChildren
  ApiGenerationReferencesRoute: typeof ApiGenerationReferencesRoute
  ApiPublicCritiquePromptRoute: typeof ApiPublicCritiquePromptRoute
  ApiPublicGeneratePromptRoute: typeof ApiPublicGeneratePromptRoute
  ApiGenerationSessionsIdRoute: typeof ApiGenerationSessionsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt': {
      id: '/prompt'
      path: '/prompt'
      fullPath: '/prompt'
      preLoaderRoute: typeof PromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/critique': {
      id: '/critique'
      path: '/critique'
      fullPath: '/critique'
      preLoaderRoute: typeof CritiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/mcp': {
      id: '/integrations/mcp'
      path: '/integrations/mcp'
      fullPath: '/integrations/mcp'
      preLoaderRoute: typeof IntegrationsMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/generate-prompt': {
      id: '/api/public/generate-prompt'
      path: '/api/public/generate-prompt'
      fullPath: '/api/public/generate-prompt'
      preLoaderRoute: typeof ApiPublicGeneratePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/critique-prompt': {
      id: '/api/public/critique-prompt'
      path: '/api/public/critique-prompt'
      fullPath: '/api/public/critique-prompt'
      preLoaderRoute: typeof ApiPublicCritiquePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generation/references': {
      id: '/api/generation/references'
      path: '/api/generation/references'
      fullPath: '/api/generation/references'
      preLoaderRoute: typeof ApiGenerationReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generation/jobs': {
      id: '/api/generation/jobs'
      path: '/api/generation/jobs'
      fullPath: '/api/generation/jobs'
      preLoaderRoute: typeof ApiGenerationJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generation/credits': {
      id: '/api/generation/credits'
      path: '/api/generation/credits'
      fullPath: '/api/generation/credits'
      preLoaderRoute: typeof ApiGenerationCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/rss.xml': {
      id: '/api/blog/rss.xml'
      path: '/api/blog/rss.xml'
      fullPath: '/api/blog/rss.xml'
      preLoaderRoute: typeof ApiBlogRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/portal': {
      id: '/api/billing/portal'
      path: '/api/billing/portal'
      fullPath: '/api/billing/portal'
      preLoaderRoute: typeof ApiBillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/confirm': {
      id: '/api/billing/confirm'
      path: '/api/billing/confirm'
      fullPath: '/api/billing/confirm'
      preLoaderRoute: typeof ApiBillingConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/account': {
      id: '/api/billing/account'
      path: '/api/billing/account'
      fullPath: '/api/billing/account'
      preLoaderRoute: typeof ApiBillingAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/username-availability': {
      id: '/api/account/username-availability'
      path: '/api/account/username-availability'
      fullPath: '/api/account/username-availability'
      preLoaderRoute: typeof ApiAccountUsernameAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/profile': {
      id: '/api/account/profile'
      path: '/api/account/profile'
      fullPath: '/api/account/profile'
      preLoaderRoute: typeof ApiAccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/delete': {
      id: '/api/account/delete'
      path: '/api/account/delete'
      fullPath: '/api/account/delete'
      preLoaderRoute: typeof ApiAccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/creations': {
      id: '/api/account/creations'
      path: '/api/account/creations'
      fullPath: '/api/account/creations'
      preLoaderRoute: typeof ApiAccountCreationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generation/sessions/$id': {
      id: '/api/generation/sessions/$id'
      path: '/api/generation/sessions/$id'
      fullPath: '/api/generation/sessions/$id'
      preLoaderRoute: typeof ApiGenerationSessionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generation/jobs/$id': {
      id: '/api/generation/jobs/$id'
      path: '/$id'
      fullPath: '/api/generation/jobs/$id'
      preLoaderRoute: typeof ApiGenerationJobsIdRouteImport
      parentRoute: typeof ApiGenerationJobsRoute
    }
  }
}

interface ApiGenerationJobsRouteChildren {
  ApiGenerationJobsIdRoute: typeof ApiGenerationJobsIdRoute
}

const ApiGenerationJobsRouteChildren: ApiGenerationJobsRouteChildren = {
  ApiGenerationJobsIdRoute: ApiGenerationJobsIdRoute,
}

const ApiGenerationJobsRouteWithChildren =
  ApiGenerationJobsRoute._addFileChildren(ApiGenerationJobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CritiqueRoute: CritiqueRoute,
  FavoritesRoute: FavoritesRoute,
  GalleryRoute: GalleryRoute,
  GenerateRoute: GenerateRoute,
  HelpRoute: HelpRoute,
  HistoryRoute: HistoryRoute,
  LibraryRoute: LibraryRoute,
  McpRoute: McpRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  PromptRoute: PromptRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BlogSlugRoute: BlogSlugRoute,
  IntegrationsMcpRoute: IntegrationsMcpRoute,
  BlogIndexRoute: BlogIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  ApiAccountCreationsRoute: ApiAccountCreationsRoute,
  ApiAccountDeleteRoute: ApiAccountDeleteRoute,
  ApiAccountProfileRoute: ApiAccountProfileRoute,
  ApiAccountUsernameAvailabilityRoute: ApiAccountUsernameAvailabilityRoute,
  ApiBillingAccountRoute: ApiBillingAccountRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingConfirmRoute: ApiBillingConfirmRoute,
  ApiBillingPortalRoute: ApiBillingPortalRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
  ApiBlogRssDotxmlRoute: ApiBlogRssDotxmlRoute,
  ApiGenerationCreditsRoute: ApiGenerationCreditsRoute,
  ApiGenerationJobsRoute: ApiGenerationJobsRouteWithChildren,
  ApiGenerationReferencesRoute: ApiGenerationReferencesRoute,
  ApiPublicCritiquePromptRoute: ApiPublicCritiquePromptRoute,
  ApiPublicGeneratePromptRoute: ApiPublicGeneratePromptRoute,
  ApiGenerationSessionsIdRoute: ApiGenerationSessionsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
