// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

function readEnv(name: string): string | undefined {
  // import.meta.env for the client bundle (Vite build-time replacement),
  // process.env for SSR.
  const fromVite = (import.meta.env as Record<string, string | undefined>)[`VITE_${name}`];
  if (fromVite) return fromVite;
  return typeof process !== "undefined" ? process.env?.[name] : undefined;
}

/**
 * True when a Supabase URL and publishable key are available. Callers that
 * can degrade (auth, library) check this instead of letting the proxy throw,
 * so a build that ran without the variables still renders the public pages.
 */
export function isSupabaseConfigured(): boolean {
  return Boolean(readEnv("SUPABASE_URL") && readEnv("SUPABASE_PUBLISHABLE_KEY"));
}

function createSupabaseClient() {
  const SUPABASE_URL = readEnv("SUPABASE_URL");
  const SUPABASE_PUBLISHABLE_KEY = readEnv("SUPABASE_PUBLISHABLE_KEY");

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error(
      "Missing Supabase environment variables. Ensure SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY (or VITE_ prefixed versions) are set in your .env file.",
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
