// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";
import { getSupabasePublicConfig, isSupabasePublicConfigured } from "@/lib/supabase-public-env";

/**
 * True when a Supabase URL and publishable key are available. Callers that
 * can degrade (auth, library) check this instead of letting the proxy throw,
 * so a build that ran without the variables still renders the public pages.
 */
export function isSupabaseConfigured(): boolean {
  return isSupabasePublicConfigured();
}

function createSupabaseClient() {
  const config = getSupabasePublicConfig();

  if (!isSupabasePublicConfigured(config)) {
    throw new Error(
      "Missing Supabase environment variables. Ensure SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY (or VITE_ prefixed versions) are set in your .env file.",
    );
  }

  return createClient<Database>(config.url, config.key, {
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
